<?php

include_once 'huvi_user_set_openid.drush.inc';

/**
 * Implements hook_menu.
 */
function huvi_user_recreate_menu() {
  $items = array();
  $items["user/%/set_openid"] = array(
    'title' => t('Add ID code'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('huvi_user_recreate_set_openid_form', 1),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}


/**
 * Generates form for add user's ID code.
 *
 * @param mixed $form
 *   The form.
 * @param mixed $form_state
 *   The state of the form.
 * @param int $uid
 *   User ID.
 *
 * @return mixed
 *   The form.
 */
function huvi_user_recreate_set_openid_form($form, &$form_state, $uid) {
  $user = user_load($uid);
  if (!$user) {
    drupal_set_message(t('User not found'), 'error');
    return;
  }
  $id_code = strstr($user->init, '@', true);

  drupal_set_title(t('User') .': ' .$user->name);
  if (!isset($form_state['uid'])) {
    $form_state['uid'] = $uid;
  }

  $form['id_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Isikukood'),
    '#default_value' => _huvi_user_recreate_id_code_validate($id_code) ? $id_code : '',
  );
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Add ID code'),
  );

  return $form;
}

/**
 *  Form validation.
 */

function huvi_user_recreate_set_openid_form_validate($form, &$form_state) {
  if (!_huvi_user_recreate_id_code_validate($form_state['values']['id_code'])) {
    form_set_error('id_code', t('ID code not valid'));
  }
}

function huvi_user_recreate_set_openid_form_submit($form, &$form_state){
  $uid = $form_state['uid'];
  $openid = $form_state['values']['id_code'];
  huvi_user_set_openid_set_openid($uid, $openid);
}

/**
 * Implements hook_user_delete().
 */
function huvi_user_recreate_user_cancel($edit, $account, $method) {

  if ('user_cancel_reassign' === $method) {
    huvi_user_recreate_create_content_sql_file($account);
  }
  // else, the method set in admin>config>account will be applicated
}

/**
 * Create a file with SQL commands. Later this file could be used to reassign user content to another user.
 *
 * @param type $account
 */
function huvi_user_recreate_create_content_sql_file($account) {
  $sql = NULL;
  $user_id = $account->uid;
  $filename = DRUPAL_ROOT. '/user-recreate/' . $user_id . '.sql';
  $id_list = NULL;

// node
  $query = db_query('SELECT n.nid FROM {node} n WHERE n.uid = :uid', array(':uid' => $user_id));
  $result = $query->fetchAll();
  $id = array();
  foreach ($result as $record) {
    $id[] = $record->nid;
  }

  if (!empty($id)) {
    $id_list = implode(', ', $id);
    $sql .= "UPDATE node SET node.uid = {?} WHERE node.nid IN ($id_list);" . PHP_EOL;
    file_put_contents($filename, "UPDATE node SET node.uid = {?} WHERE node.nid IN ($id_list);" . PHP_EOL, FILE_APPEND);
  }

// node_revision
  $query = db_query('SELECT n.nid FROM {node_revision} n WHERE n.uid = :uid', array(':uid' => $user_id));
  $result = $query->fetchAll();
  $id = array();
  foreach ($result as $record) {
    $id[] = $record->nid;
  }

  if (!empty($id)) {
    $id_list = implode(', ', $id);
    $sql .= "UPDATE node_revision SET node_revision.uid = {?} WHERE node_revision.nid IN ($id_list);" . PHP_EOL;
    file_put_contents($filename, "UPDATE node_revision SET node_revision.uid = {?} WHERE node_revision.nid IN ($id_list);" . PHP_EOL, FILE_APPEND);
  }

// file_managed
  $query = db_query('SELECT n.fid FROM {file_managed} n WHERE n.uid = :uid', array(':uid' => $user_id));
  $result = $query->fetchAll();
  $id = array();
  foreach ($result as $record) {
    $id[] = $record->fid;
  }
  if (!empty($id)) {
    $id_list = implode(', ', $id);
    $sql .= "UPDATE file_managed SET file_managed.uid = {?} WHERE file_managed.fid IN ($id_list);" . PHP_EOL;
    file_put_contents($filename, "UPDATE file_managed SET file_managed.uid = {?} WHERE file_managed.fid IN ($id_list);" . PHP_EOL, FILE_APPEND);
  }

  // Email to admin.
  $recipient = user_load(1);

  drupal_mail('huvi_user_recreate',
    'user_recreate',
    $recipient->mail,
    'et',
    $params = array('username' => $account->name,
    'userid' => $user_id,
    'sql' => $sql),
    $send = TRUE
  );
}

function huvi_user_recreate_mail($key, &$message, $params) {
  global $base_url;

  switch ($key) {
    case 'user_recreate':
      // Set headers etc
      $message['subject'] = t('User @username (ID:@userid) was removed on @site', array('@username' => $params['username'], '@userid' => $params['userid'], '@site' => $base_url));
      $message['body'][] = t('User @username (ID:@userid) was removed on @site and its content belong to the Anonymous user.', array('@username' => $params['username'], '@userid' => $params['userid'], '@site' => $base_url));
      $message['body'][] = $params['sql'];
      $message['body'][] = t('Run "drush ruc @userid {new_id}" to reassign content.', array('@username' => $params['username'], '@userid' => $params['userid'], '@site' => $base_url));
      break;
  }
}

function huvi_user_recreate_user_has_role() {
  global $user;
  $roles = func_get_args();
  foreach ($roles as $role) {
    if (in_array($role, $user->roles)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Helper function to validate the ID code.
 * @param  string $code
 * @return boolean
 */
function _huvi_user_recreate_id_code_validate($code) {

  if (!preg_match('/^(4|3|5|6)[1-9]\d{9}$/m', $code)) {
    return FALSE;
  }

  $code_segments = _huvi_user_recreate_id_code_segments($code);

  switch ((int)$code_segments['G']) {
    case 3:
    case 4:
      $year = 19 . $code_segments['YY'];
      break;
    case 5:
    case 6:
      $year = 20 . $code_segments['YY'];
      break;
    default:
      return FALSE;
  }

  // Check if birthday is a valid date.
  $month = (int) $code_segments['MM'];
  $day = (int) $code_segments['DD'];
  $year = (int) $year;
  if (!checkdate($month, $day, $year)) {
    return FALSE;
  }

  return TRUE;
}
/**
 * Helper function to segment the ID code value
 * @param  string $code
 * @return array segemented array with keys G, YY, MM, DD
 */
function _huvi_user_recreate_id_code_segments($code) {
  return array(
    'G' => substr($code, 0, 1),
    'YY' => substr($code, 1, 2),
    'MM' => substr($code, 3, 2),
    'DD' => substr($code, 5, 2)
  );
}
