<?php
/**
 * @file
 * Code for the Kultuutikava module.
 */

/**
 * Implements hook_menu().
 */
function kultuurikava_menu() {
  $items = array();

  $items['admin/config/services/kultuurikava'] = array(
    'title' => 'Kultuurikava API',
    'description' => 'Global settings for the Kultuurikava API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kultuurikava_settings_form'),
    'file' => 'kultuurikava.admin.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/services/kultuurikava/test'] = array(
    'title' => 'Test',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kultuurikava_test_form'),
    'file' => 'kultuurikava.admin.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/services/kultuurikava/api'] = array(
    'title' => 'Settings',
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items["uritus/%"] = array(
    'page callback' => 'kultuurikava_event_detail',
    'file' => 'kultuurikava.pages.inc',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items["huvitegevus/%"] = array(
    'page callback' => 'kultuurikava_event_detail',
    'file' => 'kultuurikava.pages.inc',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items["manualimport"] = array(
    'page callback' => 'kultuurikava_manual_import',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;

}


/**
 * Implements hook_cron().
 */
function kultuurikava_cron() {
  // Make API requests to Kultuurikava and save the events as nodes
  kultuurikava_import_events(variable_get('kultuurikava_cron_import_number', 50));
}


/**
 * Kultuurikava API call.
 *
 * @param array $parameters
 *   call parameters
 * @param string $api_key
 *   kultuurikava api key
 * @param string $lang
 *   language parameter
 *
 * @return array
 *   api call results
 */
function kultuurikava_api_call($parameters = array(), $api_key = NULL, $lang = NULL) {

  // Get API key.
  if (!isset($api_key)) {
    $api_key = variable_get('kultuurikava_api_key', '');
  }

  // Stop execution if API key if not set.
  if (!$api_key) {
    watchdog('kultuurikava', "No API Key configured. You must configure one at Admin->Configuration->Kultuurikava API", NULL, WATCHDOG_ERROR);
    return;
  }

  $kultuurikava_api_url = variable_get('kultuurikava_api_url', '');
  // Stop execution if Kultuurikava URL if not set.
  if (!$kultuurikava_api_url) {
    watchdog('kultuurikava', "No URL configured. You must configure one at Admin->Configuration->Kultuurikava API", NULL, WATCHDOG_ERROR);
    return;
  }

  // Default language.
  if (!isset($lang)) {
    $lang = 'nat';
  }

  // Populate the params with default data.
  $parameters += array(
    'token' => $api_key,
    'lang' => $lang,
  );

  $params = array();
  foreach ($parameters as $key => $value) {
    if (is_array($value)) {
      $value = implode(',', $value);
    }
    $param = str_replace("%7E", "~", rawurlencode($key));
    $value = str_replace("%7E", "~", rawurlencode($value));
    $params[] = $param . '=' . $value;
  }

  $query_string = implode('&', $params);
  $url = $kultuurikava_api_url . '?' . $query_string;

  // Make the request and return a JSON object.
  $results = drupal_http_request($url, array('method' => 'GET'));
  if ($results->code == 200) {

    $json_decode = drupal_json_decode($results->data);

    // Negative code means failure.
    if ($json_decode['code'] < 0) {
      watchdog('kultuurikava', "Error handling results: code=%code, message=%message.", array('%code' => $json_decode['code'], '%message' => $json_decode['message']), WATCHDOG_ERROR);
      return;
    }

    // Return results.
    return $json_decode['data'];
  }
  else {
    watchdog(
     'kultuurikava', "Error accessing Kultuurikava API with query '%url'. HTTP result code=%code, error=%error",
      array(
        '%code' => $results->code,
        '%error' => $results->error,
        '%url' => $url,
      ),
      WATCHDOG_ERROR
    );

    return;
  }

  return;
}


/**
 * Get single event by ID.
 *
 * There might be multiple events with the same id, time and place is different
 *
 * @param int $event_id
 *   event identifier
 *
 * @return array
 *   events found by id
 */
function kultuurikava_retrieve_event($event_id) {

  $parameters = array(
    'do' => 'events',
    'id' => $event_id,
    'date' => '1990-01-01',
    'county' => 'tallinn',
    'order' => 'starta',
  );

  $events = kultuurikava_api_call($parameters, NULL, 'nat');

  return $events;
}


function kultuurikava_get_event_data($event_id) {

  $items = kultuurikava_retrieve_event($event_id);

  if (empty($items['events'])) {
    return;
  }

  $event = array(
    'id' => '',
    'name' => '',
    'excerpt' => '',
    'description' => '',
    'hasimage' => FALSE,
    'image' => '',
    'video' => '',
    'pre_description' => array(),
    'map_latlng' => '',
    'map_markers' => '',
    'type' => 'uritus',
  );

  $data_markers = array();

  $fields = kultuurikava_event_to_node_fields();
  foreach($fields as $field => $node_field) {
    if (isset($items['events'][0][$field]) && !empty($items['events'][0][$field])) {
      $event[$field] = $items['events'][0][$field];
    }
  }

  // Type.
  if (isset($items['events'][0]['recreation']) && !empty($items['events'][0]['recreation'])) {
    if ($items['events'][0]['recreation'] == TRUE) {
      $event['type'] = 'huvitegevus';
    }
  }

  // Schedule and map.
  foreach ($items['events'] as $key => $single_event) {

    if (isset($single_event['start_time']) && !empty($single_event['start_time'])) {
      $event['schedule'][$key]['start_time'] = $single_event['start_time'];
    }

    if (isset($single_event['end_time']) && !empty($single_event['end_time'])) {
      $event['schedule'][$key]['end_time'] = $single_event['end_time'];
    }

    // Place.
    $place = array();
    $places = kultuurikava_retrieve_place($single_event['place_id']);

    if (isset($places['places']) && !empty($places['places'])) {

      if (isset($places['places'][0]['name']) && !empty($places['places'][0]['name'])) {
        $place[] = $places['places'][0]['name'];
      }
      if (isset($places['places'][0]['address']) && !empty($places['places'][0]['address'])) {
        $place[] = $places['places'][0]['address'];
      }
      if (isset($places['places'][0]['city_id']) && !empty($places['places'][0]['city_id'])) {
        $event['schedule'][$key]['city_id'] = $places['places'][0]['city_id'];
      }

      $place[] = 'Tallinn';

      $event['schedule'][$key]['place'] = implode(', ', $place);

      if (isset($places['places'][0]['coordinates']['lat'])
          && !empty($places['places'][0]['coordinates']['lat'])
          && isset($places['places'][0]['coordinates']['lng'])
          && !empty($places['places'][0]['coordinates']['lng'])) {
        $new_place = $places['places'][0]['coordinates']['lat'] . ',' . $places['places'][0]['coordinates']['lng'];
        if(!in_array($new_place, $data_markers)) {
          $data_markers[] = $new_place;
        }
      }

    }
  }

  if (isset($data_markers) && !empty($data_markers)) {

    $data_latlng_plain = $data_markers[0];
    $data_markers_plain = implode(';', $data_markers);

    $event['map_latlng'] = $data_latlng_plain;
    $event['map_markers'] = $data_markers_plain;
    //drupal_add_js('//maps.googleapis.com/maps/api/js?sensor=false', 'external');

  }

  // Attributes.
  if (isset($items['events'][0]['attributes']) && !empty($items['events'][0]['attributes'])) {
    if (isset($items['events'][0]['attributes']['pre_description']) && !empty($items['events'][0]['attributes']['pre_description'])) {
      $event['pre_description'] = $items['events'][0]['attributes']['pre_description'];
    }
  }

  return $event;
}


/**
 * Get place by ID.
 *
 * @param int $place_id
 *   Place identifier
 *
 * @return array
 *   places found by id
 */
function kultuurikava_retrieve_place($place_id) {

  $parameters = array(
    'do' => 'places',
    'id' => $place_id,
  );

  $places = kultuurikava_api_call($parameters, NULL, 'nat');

  return $places;

}


/**
 * Implements hook_theme().
 */
function kultuurikava_theme() {
  return array(
    'kultuurikava_event_detail' => array(
      'arguments' => array('event' => NULL),
      'template' => 'templates/kultuurikava_event_detail',
    ),
  );
}


/**
 * Get Drupal categories with slugs as key.
 *
 * @return array
 *   categories
 */
function kultuurikava_get_categories($section = 'events') {

  // Default parent category.
  $parent = 0;

  // Get parent category.
  $parent_category = kultuurikava_get_parent_category($section);

  if (isset($parent_category) && !empty($parent_category)) {
    $parent = $parent_category[0];
  }

  $tree = taxonomy_get_tree($vid = 4, $parent, $max_depth = 1, $load_entities = TRUE);
  $categories = array();
  foreach ($tree as $term) {
    if (module_exists('i18n_taxonomy')) {
      $term = i18n_taxonomy_localize_terms($term);
    }

    $slug = $term->field_slug[LANGUAGE_NONE][0]['value'];

    $categories[$slug] = $term->name;
  }

  return $categories;
}


/**
 * Get Parent category.
 *
 * @param string $section
 *   category section. event or activity.
 */
function kultuurikava_get_parent_category($section) {

  // Get parent term id.
  $query = db_select('taxonomy_term_data', 't');
  $query->innerJoin('field_data_field_slug', 's', 't.tid = s.entity_id');
  $query->fields('t', array('tid'));
  $query->condition('t.vid', 4);
  $query->condition('s.bundle', 'categories');
  $query->condition('s.field_slug_value', $section);
  $result = $query->execute()->fetchCol();

  return $result;
}


/**
 * Get internal categories by kultuurikava category id.
 *
 * @param int $category_id
 *   kultuurikava category id
 *
 * @return array
 *   internal categories
 */
function kultuurikava_get_category_by_kk_id($category_id, $section) {

  // Get parent category.
  $parent_category = kultuurikava_get_parent_category($section);
  if (isset($parent_category) && !empty($parent_category)) {
    $parent = $parent_category[0];
  }
  else {
    $parent = 0;
  }

  // Get categories where referencing term id = $category_id
  $query = db_select('taxonomy_term_data', 't');
  $query->innerJoin('field_data_field_kultuurikava_categories', 'kc', 't.tid = kc.entity_id');
  $query->innerJoin('field_data_field_category_id', 'ci', 'kc.field_kultuurikava_categories_tid = ci.entity_id');
  $query->innerJoin('taxonomy_term_hierarchy', 'h', 't.tid = h.tid');
  $query->fields('t', array('name', 'tid'));
  $query->condition('t.vid', 4);
  $query->condition('ci.field_category_id_value', $category_id);
  $query->condition('h.parent', $parent);
  $query->orderBy('t.weight', 'ASC');
  $categories = $query->execute()->fetchAll();

  if ($categories && module_exists('i18n_taxonomy')) {
    foreach ($categories as $key => $category) {
      $term = taxonomy_term_load($category->tid);
      $term = i18n_taxonomy_localize_terms($term);
      $categories[$key]->name = $term->name;
    }
    return $categories;
  }

  return;
}


/**
 * Get kultuurikava slugs by own category slug.
 *
 * @param string $category_slug
 *   own category slug
 *
 * @return array
 *   result
 */
function kultuurikava_get_kk_categories_by_slug($category_slug, $section) {

  // Get parent category.
  $parent_category = kultuurikava_get_parent_category($section);
  if (isset($parent_category) && !empty($parent_category)) {
    $parent = $parent_category[0];
  }
  else {
    $parent = 0;
  }

  $result = array();

  $query = db_select('taxonomy_term_data', 't');
  $query->innerJoin('field_data_field_slug', 's', 't.tid = s.entity_id');
  $query->innerJoin('taxonomy_term_hierarchy', 'h', 't.tid = h.tid');
  $query->fields('t', array('tid', 'name'));
  $query->condition('t.vid', 4);
  $query->condition('s.field_slug_value', $category_slug);
  $query->condition('h.parent', $parent);
  $query->orderBy('t.weight', 'ASC');
  $query->range(0, 1);
  $categories = $query->execute()->fetchAll();

  if ($categories) {

    $term = taxonomy_term_load($categories[0]->tid);
    if (isset($term->field_kultuurikava_categories[LANGUAGE_NONE]) && !empty($term->field_kultuurikava_categories[LANGUAGE_NONE])) {

      foreach ($term->field_kultuurikava_categories[LANGUAGE_NONE] as $reference) {

        $kk_term = taxonomy_term_load($reference['tid']);
        if (isset($kk_term->field_slug[LANGUAGE_NONE]) && !empty($kk_term->field_slug[LANGUAGE_NONE])) {
          foreach ($kk_term->field_slug[LANGUAGE_NONE] as $slug) {
            $result[] = $slug['value'];
          }
        }
      }

    }
  }

  return $result;
}


/**
 * Ticket link.
 *
 * @param array $ticket
 *   ticket array with name, logo, and provider information
 *
 * @return string
 *   rendered link
 */ 
function kultuurikava_ticket_link($ticket) {
	$base_path = $GLOBALS['base_path'];
	$link_content = $ticket['provider']['name'];
	$link = l($link_content, $ticket['ticketurl'], array('attributes' => array('target' => '_blank')));
 
  if ($ticket['provider']['logo']) {
    $logo_url = drupal_get_path('theme', 'huvi') . '/images/ticketproviders/' . $ticket['provider']['logo'];
	
    if(file_exists($logo_url)) {
      $link_content = '<img src="/' . $base_path . $logo_url . '" />';
      $link = l($link_content, $ticket['ticketurl'], array('attributes' => array('target' => '_blank'), 'html' => TRUE));
    }
  }

  return $link;
}


/**
 * Make API requests to Kultuurikava and save the events as nodes
 */
function kultuurikava_import_events($limit = 50) {
  // Is the first import done or not
  $first_import_done = variable_get('kultuurikava_import_first_done', FALSE);
  // this increments after each function run for decreasing load on cron and API calls
  $page = variable_get('kultuurikava_import_next_page', 0);
  $last_page = FALSE;

  $start = $page * $limit;
  //$date = date('Y-m-d');
  // Take all events from the start of this year, in case the end time might still be later than today
  $date = date('Y-m-01');
  $parameters = array(
    'do' => 'events',
    'start' => $start,
    'limit' => $limit,
    'group' => 'true',
    'date' => $date,
    'county' => 'tallinn',
    'order' => 'createda', // works and should be used for initial import
    //'order' => 'starta',
    //'recreation' => 'true',
  );

  if($first_import_done) {
    $modified = variable_get('kultuurikava_import_last_time', FALSE);
    if(!$modified) {
      watchdog('kultuurikava', 'kultuurikava_import_last_time variable not set. This should be done automatically in code.', NULL, WATCHDOG_ERROR);
      return;
    }
    $parameters['modified'] = $modified;
    unset($parameters['date']);
  }

  // Get a list of events for IDs at first
  // (note that there are no multiple schedule items in the general calls
  // that's why we need to make individual API calls for each event later)
  $events = kultuurikava_api_call($parameters, NULL, 'nat');

  if (isset($events['events']) && !empty($events['events'])) {
    // Array of event IDs from which to loop and get events by ID
    $event_ids = array();
    foreach($events['events'] as $event_key => $event) {
      $event_ids[] = $event['id'];
    }
    $i = 0;
    foreach($event_ids as $event_id_key => $event_id) {
      // Get the specific event node and save it as an event node to Drupal
      kultuurikava_event_data_node_save(kultuurikava_get_event_data($event_id));
      $i++;
    }
    $progress = $start + $i;
    $progress_text = 'Imported/updated ' . $i . ' events. Progress: ' . $progress . '/' . $events['total'];
    watchdog('kultuurikava', $progress_text, NULL, WATCHDOG_INFO);
    variable_set('kultuurikava_import_progress_text', $progress_text);
    // There are more items to import on the next page
    if($events['total'] >= $start + $limit) {
      variable_set('kultuurikava_import_next_page', $page + 1);
    }
    else {
      $last_page = TRUE;
      variable_set('kultuurikava_import_last_time', time());
      if(!$first_import_done) {
        variable_set('kultuurikava_import_first_done', TRUE);
        watchdog('kultuurikava', 'Initial import of all Kultuurikava events is now completed.', NULL, WATCHDOG_INFO);
      }
    }
  }
  else {
    $last_page = TRUE;
    watchdog('kultuurikava', 'Cron ran. Empty events results.', NULL, WATCHDOG_INFO);
    variable_set('kultuurikava_import_progress_text', 'No new events to import');
  }

  // Run this if this is the last page to be imported
  if($last_page) {
    variable_set('kultuurikava_import_next_page', 0);
  }
}


/**
 * Save event from Kultuurikava as a node
 *
 * @return array $return
 *   Event data fields as keys and node fields as values
 */
function kultuurikava_event_to_node_fields() {
  $return = array(
    'id' => 'field_id',
    'name' => 'title',
    'excerpt' => 'field_excerpt',
    'description' => 'field_description',
    'hasimage' => 'field_hasimage',
    'image' => 'field_image_url',
    'video' => 'field_video_url',
    'pre_description' => 'field_pre_description',
    'map_latlng' => 'field_map_latlng',
    'map_markers' => 'field_map_markers',
    'type' => 'field_type',
    'ticketurl' => 'field_tickets',
    'schedule' => 'field_schedule',
    'isfree' => 'field_isfree',
    'categories' => 'field_categories_event',
  );
  return $return;
}


/**
 * Get ticket seller names
 *
 * @return array $return
 *   Ticket seller names for getting images
 */
function kultuurikava_get_ticket_seller_name($nr) {
  // TODO: Check that these names correspond to the ones sent from kultuurikava API
  $return = array(
    'Artis' => 1,
    'Cinamon' => 2,
    'Forum Cinemas' => 3,
    'Piletilevi' => 4,
    'Piletimaailm' => 5,
    'solariskino.ee' => 6,
    // www.gateme.com
  );
  if($nr) {
    $return_one = $return[$nr];
    if($return_one) {
      $return = $return_one;
    }
  }
  return $return;
}


/**
 * Get ticket seller image filename
 *
 * @return array $return
 *   Ticket seller logo filenames or just one specific filename
 */
function kultuurikava_get_ticket_seller_image($nr) {
  $return = array(
    'kino.ee' => 'artiskino_logo.jpg',
    'cinamon.ee' => 'cinamon_logo.png',
    'forumcinemas.ee' => 'forumcinemas_logo.jpg',
    'piletilevi.ee' => 'piletilevi_logo.gif',
    'piletimaailm.com' => 'piletimaailm_logo.gif',
    'solariskino.ee' => 'solariskino_logo.jpg',
  );
  if($nr) {
    if(isset($return[$nr])) {
      $return_one = $return[$nr];
      if($return_one) {
        return $return_one;
      }
      return;
    }
    return;
  }
  return $return;
}


/**
 * Get cities from city_id-s from kultuurikava
 *
 * @return array $return
 *   Ticket seller names for getting images
 */
function kultuurikava_city_from_id($city_id) {
  $cities = array(
    2944195 => 'pohja-tallinn',
    2944191 => 'kesklinn',
    2944198 => 'kesklinn', // vanalinn
    2944188 => 'kesklinn', // kadriorg
    2944187 => 'haabersti',
    2944189 => 'kristiine',
    2944190 => 'lasnamae',
    2944193 => 'mustamae',
    2920234 => 'pirita',
    2944194 => 'nomme',
  );
  if($city_id) {
    $city = $cities[$city_id];
    if($city) {
      return $city;
    }
    watchdog('kultuurikava', 'No city found with city_id: ' . $city_id, NULL, WATCHDOG_ERROR);
  }
  else {
    return $cities;
  }
}


/**
 * Get categories based on Kultuurikava category IDs
 *
 * @return array $return
 *   Category IDs to save to drupal
 */
function kultuurikava_event_categories_by_kk_ids($categories, $event_type) {
  /*
  0|Muusika
  1|Etendused
  2|Näitus, muuseum
  3|Mess, laat
  4|Sport
  5|Kino
  6|Pidu, klubid
  7|Lapsele
  8|Varia
  */
  $event = array(
    14453 => 0,
    369755 => 0,
    14452 => 1,
    14455 => 2,
    14465 => 2,
    14459 => 3,
    14456 => 4,
    14454 => 5,
    14457 => 6,
    160542 => 6,
    14458 => 7,
    5218297 => 8,
    5218295 => 8,
    14460 => 8,
    5218296 => 8,
    14463 => 8,
    14461 => 8,
    14462 => 8,
    14466 => 8,
    14464 => 8,
  );

  /*
  0|Muusika
  1|Kunst, käsitöö
  2|Tantsimine
  3|Sport, liikumine
  4|Tehnika
  5|Keeleõpe
  6|Koolitused, kursused
  7|Lapsele
  8|Varia
  */
  $activity = array(
    14453 => 0,
    5218295 => 1,
    369755 => 2,
    14456 => 3,
    5218296 => 4,
    5218297 => 5,
    160542 => 6,
    14458 => 7,
    14460 => 8,
    14452 => 8,
    14455 => 8,
    14465 => 8,
    14459 => 8,
    14454 => 8,
    14457 => 8,
    14463 => 8,
    14461 => 8,
    14462 => 8,
    14466 => 8,
    14464 => 8,
  );

  if($categories) {
    $list = $event;
    if($event_type == 'huvitegevus') {
      $list = $activity;
    }
    $return = array();
    foreach($categories as $key => $kk_id) {
      $return[] = $list[$kk_id];
    }
    return $return;
  }
  else {
    watchdog('kultuurikava', 'Category was empty to get event category listing', NULL, WATCHDOG_ERROR);
    return;
  }
}


/**
 * Save event from Kultuurikava as a node
 *
 * @param array $event_id
 *   Event ID of the Kultuurikava event
 */
function kultuurikava_event_data_node_save($event) {
  if(!$event) {
    watchdog('kultuurikava', "No event data found in function kultuurikava_event_data_node_save", NULL, WATCHDOG_ERROR);
    return;
  }
  $e = $event;
  // Check if the node exists already
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->fieldCondition('field_id', 'value', $e['id'], '=')
    ->execute();
  // Node exists, load the entity
  if($result) {
    foreach($result['node'] as $key => $val) {
      $entity_load = entity_load('node', array($key));
      foreach($entity_load as $ekey => $eval) {
        $entity = $eval;
      }
    }
  }
  // Node doesn't exist yet, create a new entity
  else {
    $values = array(
      'type' => 'event',
      'uid' => 1,
      'status' => 1,
      'comment' => 0,
      'promote' => 0,
      'language' => 'et',
    );
    $entity = entity_create('node', $values);
  }

  $w = entity_metadata_wrapper('node', $entity);
  $fields = kultuurikava_event_to_node_fields();
  foreach($fields as $event_item => $field) {
    if(isset($e[$event_item])) {
      switch($event_item) {
        case 'schedule':
          // Get and remove all the existing field collection items and save them again (because there might be changes)
          if(!empty($entity->field_schedule['und'])) {
            $s_values = array();
            foreach($entity->field_schedule['und'] as $s_key => $s_val) {
              $s_values[] = $s_val['value'];
              unset($entity->field_schedule['und'][$s_key]);
            }
            if(!empty($s_values)) {
              entity_delete_multiple('field_collection_item', $s_values);
            }
          }
          foreach($e['schedule'] as $key => $val) {
            $schedule_item = entity_create('field_collection_item', array('field_name' => 'field_schedule'));
            $schedule_item->setHostEntity('entity', $entity);
            $schedule_wrapper = entity_metadata_wrapper('field_collection_item', $schedule_item);

            if($val['start_time'] && is_int($val['start_time'])) {
              if(is_int($val['end_time']) && $val['end_time'] < 2000000000) {
                $schedule_wrapper->field_schedule_date[0]->set(array(
                  'value' => $val['start_time'],
                  'value2' => $val['end_time'],
                ));
              }
              else {
                $schedule_wrapper->field_schedule_date[0]->set(array(
                  'value' => $val['start_time'],
                ));
              }
            }
            if($val['city_id'] == '2944198' || $val['city_id'] == '2944188') {
              $val['city_id'] = 2944191;
            }
            $schedule_wrapper->field_schedule_place->set($val['place']);
            $schedule_wrapper->field_schedule_city_id->set($val['city_id']);
          }
          break;
        case 'ticketurl':
          $ticket_urls = array();
          foreach($e[$event_item] as $key => $val) {
            $ticket_urls[] = $val['ticketurl'];
          }
          if(!empty($ticket_urls)) {
            $w->{$field}->set($ticket_urls);
          }
          break;
        case 'categories':
          $field_name = 'field_categories_event';
          if($e['type'] == 'huvitegevus') {
            $field_name = 'field_categories_activity';
          }
          $categories = array();
          foreach($e[$event_item] as $category_id) {
            $categories = kultuurikava_event_categories_by_kk_ids($e[$event_item], $e['type']);
          }
          if(!empty($categories)) {
            $w->{$field_name}->set($categories);
          }
          break;
        case 'description':
          $w->{$field}->value->set($e[$event_item]);
          break;
        case 'type':
          $w->{$field}->set($e[$event_item]);
          break;
        default:
          $w->{$field}->set($e[$event_item]);
          break;
      }
    }
  }

  $w->save();
}


/**
 * Convert node to proper event fields displayed on the event node template page
 *
 * @param object $node
 *   Event node to be converted to the event array
 *
 * @return array $e
 *   Event data for showing in the event template on the node page
 */
function kultuurikava_node_to_event($node) {
  $n = $node;
  $e = array();
  $addedMarkers = array();
  $fields = kultuurikava_event_to_node_fields();

  // If the event has sub-events set
  $sub_event_ids = kultuurikava_get_sub_event_ids($n->nid);
  if(isset($sub_event_ids)) {
    $sub_events = array();
    foreach($sub_event_ids as $sub_event_id) {
      $sub_event = kultuurikava_get_sub_event($sub_event_id);
      if(isset($sub_event)) {
        $sub_events[] = $sub_event;
      }
    }
    if(isset($sub_events)) {
      $e['sub_events'] = $sub_events;
    }
  }

  // If the event has a main event set
  if(isset($n->field_main_event_ref['und'][0]['node'])) {
    $main_node = $n->field_main_event_ref['und'][0]['node'];
    if($main_node->status == '1') {
      $e['main_event'] = array(
        'title' => $main_node->title,
        'path' => url('node/' . $main_node->nid),
      );
    }
  }

  foreach($fields as $event => $field) {
    switch($event) {
      case 'name':
        $e[$event] = $n->{$field};
        break;
      case 'schedule':
        if(isset($n->{$field}['und'])) {
          $date_format = 'D, d.m.Y H:i';
          $short_date_format = 'D, d.m.Y';
          $event_key = 0;
          foreach($n->{$field}['und'] as $key => $val) {
           if (isset($val['value'])) {
            $collections = entity_load('field_collection_item', array($val['value']));
            foreach($collections as $c) {

              if(isset($c->field_schedule_date['und'])) {
                foreach($c->field_schedule_date['und'] as $time_key => $time) {
                  if(isset($time['value'])) {
                    $start_date = $time['value'];                    
                    if(isset($time['value2'])) {
                      $end_date = $time['value2'];
                    }
                    $e[$event][$event_key]['asort'] = $start_date;
                    if(isset($end_date)) {
                      // No need to show the ending date, when it's the same as the starting date
                      if($start_date == $end_date) {
                        if (date('H:i', $start_date) == '23:55')
                          $e[$event][$event_key]['time'] = format_date($start_date, 'custom', $short_date_format) . ' ' . t('Terve päev');
                        else
                          $e[$event][$event_key]['time'] = format_date($start_date, 'custom', $date_format);
                      }
                      else {
                        $e[$event][$event_key]['time'] = format_date($start_date, 'custom', $date_format)
                          . ' - '
                          . format_date($end_date, 'custom', $date_format);
                      }
                    }
                    else {
                      if (date('H:i', $start_date) == '23:55')
                          $e[$event][$event_key]['time'] = format_date($start_date, 'custom', $short_date_format) . ' ' . t('Terve päev');
                        else
                          $e[$event][$event_key]['time'] = format_date($start_date, 'custom', $date_format);
                    }
                    $e[$event][$event_key]['place'] = $c->field_schedule_place['und'][0]['value'];
                    $event_key++;
                  }
                }
              }

              // Read manually inserted markers only when no imported ones were detected
              if(isset($c->field_schedule_location['und'][0]['lat']) && isset($c->field_schedule_location['und'][0]['lng'])) {
                $marker = $c->field_schedule_location['und'][0]['lat'] . ',' . $c->field_schedule_location['und'][0]['lng'];
                if(!isset($e['map_latlng'])) {
                  $addedMarkers['map_latlng'] = $marker;
                }
                if(isset($addedMarkers['map_markers'])) {
                  $addedMarkers['map_markers'] .= ';' . $marker;
                }
                else {
                  $addedMarkers['map_markers'] = $marker;
                }
              }
            }
          }
         } 
        }
        break;
      case 'ticketurl':
        if(isset($n->{$field}['und'])) {
          foreach($n->{$field}['und'] as $key => $url) {
            $url_parse = parse_url($url['value']);
            if(!isset($url_parse['host'])) {
              $url_parse = explode('/', $url_parse['path']);
              $url_host = $url_parse[0];
              $url['value'] = 'http://' . $url['value'];
			  
            }
            else {
              $url_host = $url_parse['host'];
            }
            if (substr($url_host, 0, strlen('www.')) == 'www.') {
              $url_host = substr($url_host, strlen('www.'));
            }
            $link_content = $url_host;
            $logo_filename = kultuurikava_get_ticket_seller_image($url_host);
            if(!empty($logo_filename)) {
			  $base_path = $GLOBALS['base_path'];
              $logo_url = drupal_get_path('theme', 'huvi') . '/images/ticketproviders/img/' . $logo_filename;
              if(file_exists($logo_url)) {
                $link_content = '<img src="/' . $base_path . $logo_url . '" alt="' . $url_host . '" />';
              }
            }
            $t_link = l($link_content, $url['value'], array('attributes' => array('target' => '_blank'), 'html' => TRUE));
            $e[$event][$key] = $t_link;
          }
        }
        break;
      default:
        if(isset($n->{$field}['und'])) {
          if(isset($n->{$field}['und'][0]['value'])) {
            $e[$event] = $n->{$field}['und'][0]['value'];
          }
        }
        break;
    }
  }
  // If no markers are imported (most probably event was added manually),
  // then add the manually added markers if they exist
  if(!isset($e['map_markers']) && isset($addedMarkers['map_markers'])) {
    $e['map_markers'] = $addedMarkers['map_markers'];
    $e['map_latlng'] = $addedMarkers['map_latlng'];
  }

  return $e;
}


/**
 * Get sub events by node ID
 *
 * @param object $node_id
 *   Event node ID of which to get sub events from
 *
 * @return array $sub_events
 *   Sub events data
 */
function kultuurikava_get_sub_event_ids($node_id) {
  // Get parent term id.
  $query = db_select('field_data_field_main_event_ref', 'f');
  $query->fields('f', array('entity_id'));
  $query->condition('f.field_main_event_ref_nid', $node_id);
  $results = $query->execute()->fetchAll();
  $sub_event_ids = array();
  if($results) {
    foreach($results as $result) {
      $sub_event_ids[] = $result->entity_id;
    }
    return $sub_event_ids;
  }
  return;
}


/**
 * Get sub events by node ID
 *
 * @param object $node_id
 *   Event node ID of which to get the sub event data
 *
 * @return array $sub_events
 *   Data usable for event node view
 */
function kultuurikava_get_sub_event($node_id) {
  // Get parent term id.
  $node = node_load($node_id);
  // Use only published nodes
  if($node->status == '1') {
    $return['title'] = $node->title;
    $return['path'] = url('node/' . $node->nid);

    return $return;
  }
  return;
}


/**
 * Manually execute cron function for importing events from Kultuurikava API
 */
function kultuurikava_manual_import() {
  kultuurikava_cron();
  print t('Importing kultuurikava items...') . '<br>';
  print variable_get('kultuurikava_import_progress_text', 'updating status.') . '<br>';
  if(variable_get('kultuurikava_import_first_done') == TRUE) {
    print t('Refreshing automatically after every 3 minutes.') . '<br>';
    header("Refresh: 180;");
  }
  else {
    print t('Refreshing automatically after every 2 seconds.') . '<br>';
    header("Refresh: 2;");
  }
}
