<?php

/**
 * @file
 * Code for the Kultuutikava module.
 */

/**
 * Implements hook_menu().
 */
function kultuurikava_menu() {
  $items = array();

  $items['admin/config/services/kultuurikava'] = array(
    'title' => 'Kultuurikava API',
    'description' => 'Global settings for the Kultuurikava API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kultuurikava_settings_form'),
    'file' => 'kultuurikava.admin.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/services/kultuurikava/test'] = array(
    'title' => 'Test',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kultuurikava_test_form'),
    'file' => 'kultuurikava.admin.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/services/kultuurikava/api'] = array(
    'title' => 'Settings',
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  /*$items["uritus/%"] = array(
    'page callback' => 'kultuurikava_event_detail',
    'file' => 'kultuurikava.pages.inc',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items["huvitegevus/%"] = array(
    'page callback' => 'kultuurikava_event_detail',
    'file' => 'kultuurikava.pages.inc',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );*/

  $items["manualimport"] = array(
    'page callback' => 'kultuurikava_manual_import',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
   $items['subevents/get/ajax'] = array(
    'page callback' => 'kultuurikava_ajax_get_subevents', // Render HTML.
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;

}
/*
 * Ajax call
 */
function kultuurikava_ajax_get_subevents(){
  $active_filters = $_POST['filters'];
  $nid=$_POST['nid'];
  if (isset($_POST['start_date']) && isset($_POST['end_date'])) {
    $active_filters['period'] = array('start_date' => $_POST['start_date'], 'end_date' => $_POST['end_date']);
  }

  if(isset($active_filters['type'])){
   $active_filters['type'] = _kultuurikava_mapping_event_categories_to_filters($active_filters['type']);
  }

  $sub_events = kultuurikava_get_subevents($nid, $active_filters);
  print theme('kultuurikava_subevents', array(
    'subevents' => $sub_events)
  );
}

/**
 * Implements hook_cron().
 */
function kultuurikava_cron() {
  // Make API requests to Kultuurikava and save the events as nodes
  kultuurikava_import_events(variable_get('kultuurikava_cron_import_number', 50));
}


/**
 * Kultuurikava API call.
 *
 * @param array $parameters
 *   call parameters
 * @param string $api_key
 *   kultuurikava api key
 * @param string $lang
 *   language parameter
 *
 * @return array
 *   api call results
 */
function kultuurikava_api_call($parameters = array(), $api_key = NULL, $lang = NULL) {

  // Get API key.
  if (!isset($api_key)) {
    $api_key = variable_get('kultuurikava_api_key', '');
  }

  // Stop execution if API key if not set.
  if (!$api_key) {
    watchdog('kultuurikava', "No API Key configured. You must configure one at Admin->Configuration->Kultuurikava API", NULL, WATCHDOG_ERROR);
    return;
  }

  $kultuurikava_api_url = variable_get('kultuurikava_api_url', '');
  // Stop execution if Kultuurikava URL if not set.
  if (!$kultuurikava_api_url) {
    watchdog('kultuurikava', "No URL configured. You must configure one at Admin->Configuration->Kultuurikava API", NULL, WATCHDOG_ERROR);
    return;
  }

  // Default language.
  if (!isset($lang)) {
    $lang = 'nat';
  }

  // Populate the params with default data.
  $parameters += array(
    'token' => $api_key,
    'lang' => $lang,
  );

  $params = array();
  foreach ($parameters as $key => $value) {
    if (is_array($value)) {
      $value = implode(',', $value);
    }
    $param = str_replace("%7E", "~", rawurlencode($key));
    $value = str_replace("%7E", "~", rawurlencode($value));
    $params[] = $param . '=' . $value;
  }

  $query_string = implode('&', $params);
  $url = $kultuurikava_api_url . '?' . $query_string;

  // Make the request and return a JSON object.
  $results = drupal_http_request($url, array('method' => 'GET'));
  if ($results->code == 200) {

    $json_decode = drupal_json_decode($results->data);

    // Negative code means failure.
    if ($json_decode['code'] < 0) {
      watchdog('kultuurikava', "Error handling results: code=%code, message=%message.", array('%code' => $json_decode['code'], '%message' => $json_decode['message']), WATCHDOG_ERROR);
      return;
    }

    // Return results.
    return $json_decode['data'];
  }
  else {
    watchdog(
     'kultuurikava', "Error accessing Kultuurikava API with query '%url'. HTTP result code=%code, error=%error",
      array(
        '%code' => $results->code,
        '%error' => $results->error,
        '%url' => $url,
      ),
      WATCHDOG_ERROR
    );

    return;
  }

  return;
}


/**
 * Get single event by ID.
 *
 * There might be multiple events with the same id, time and place is different
 *
 * @param int $event_id
 *   event identifier
 *
 * @return array
 *   events found by id
 */
function kultuurikava_retrieve_event($event_id) {

  $parameters = array(
    'do' => 'events',
    'id' => $event_id,
    'date' => '1990-01-01',
    'county' => 'tallinn',
    'order' => 'starta',
  );

  $events = kultuurikava_api_call($parameters, NULL, 'nat');

  return $events;
}


function kultuurikava_get_event_data($event_id) {

  $items = kultuurikava_retrieve_event($event_id);

  if (empty($items['events'])) {
    return;
  }

  $event = array(
    'id' => '',
    'name' => '',
    'excerpt' => '',
    'description' => '',
    'hasimage' => FALSE,
    'image' => '',
    'video' => '',
    'pre_description' => array(),
    'map_latlng' => '',
    'map_markers' => '',
    'type' => 'uritus',
  );

  $data_markers = array();

  $fields = kultuurikava_event_to_node_fields();
  foreach($fields as $field => $node_field) {
    if (isset($items['events'][0][$field]) && !empty($items['events'][0][$field])) {
      $event[$field] = $items['events'][0][$field];
    }
  }

  // Type.
  if (isset($items['events'][0]['recreation']) && !empty($items['events'][0]['recreation'])) {
    if ($items['events'][0]['recreation'] == TRUE) {
      $event['type'] = 'huvitegevus';
    }
  }

  // Schedule and map.
  foreach ($items['events'] as $key => $single_event) {

    if (isset($single_event['start_time']) && !empty($single_event['start_time'])) {
      $event['schedule'][$key]['start_time'] = $single_event['start_time'];
    }

    if (isset($single_event['end_time']) && !empty($single_event['end_time'])) {
      $event['schedule'][$key]['end_time'] = $single_event['end_time'];
    }

    // Place.
    $place = array();
    $places = kultuurikava_retrieve_place($single_event['place_id']);

    if (isset($places['places']) && !empty($places['places'])) {

      if (isset($places['places'][0]['name']) && !empty($places['places'][0]['name'])) {
        $place[] = $places['places'][0]['name'];
      }
      if (isset($places['places'][0]['address']) && !empty($places['places'][0]['address'])) {
        $place[] = $places['places'][0]['address'];
      }
      if (isset($places['places'][0]['city_id']) && !empty($places['places'][0]['city_id'])) {
        $event['schedule'][$key]['city_id'] = $places['places'][0]['city_id'];
      }

      $place[] = 'Tallinn';

      $event['schedule'][$key]['place'] = implode(', ', $place);

      if (isset($places['places'][0]['coordinates']['lat'])
          && !empty($places['places'][0]['coordinates']['lat'])
          && isset($places['places'][0]['coordinates']['lng'])
          && !empty($places['places'][0]['coordinates']['lng'])) {
        $new_place = $places['places'][0]['coordinates']['lat'] . ',' . $places['places'][0]['coordinates']['lng'];
        if(!in_array($new_place, $data_markers)) {
          $data_markers[] = $new_place;
        }
      }

    }
  }

  if (isset($data_markers) && !empty($data_markers)) {

    $data_latlng_plain = $data_markers[0];
    $data_markers_plain = implode(';', $data_markers);

    $event['map_latlng'] = $data_latlng_plain;
    $event['map_markers'] = $data_markers_plain;
    //drupal_add_js('//maps.googleapis.com/maps/api/js?sensor=false', 'external');

  }

  // Attributes.
  if (isset($items['events'][0]['attributes']) && !empty($items['events'][0]['attributes'])) {
    if (isset($items['events'][0]['attributes']['pre_description']) && !empty($items['events'][0]['attributes']['pre_description'])) {
      $event['pre_description'] = $items['events'][0]['attributes']['pre_description'];
    }
  }

  return $event;
}


/**
 * Get place by ID.
 *
 * @param int $place_id
 *   Place identifier
 *
 * @return array
 *   places found by id
 */
function kultuurikava_retrieve_place($place_id) {

  $parameters = array(
    'do' => 'places',
    'id' => $place_id,
  );

  $places = kultuurikava_api_call($parameters, NULL, 'nat');

  return $places;

}


/**
 * Implements hook_theme().
 */
function kultuurikava_theme() {
  return array(
    'kultuurikava_event_detail' => array(
      'arguments' => array('event' => NULL),
      'template' => 'templates/kultuurikava_event_detail',
    ),
    'kultuurikava_subevents_block' => array(
      'variables' => array('parent_nid' => NULL, 'subevents' => NULL, 'filters' => NULL, 'existing_filters' => NULL, 'active_filters' => NULL),
      'template' => 'templates/kultuurikava_subevents_block',
    ),
    'kultuurikava_subevents' => array(
      'variables' => array('subevents' => NULL),
      'template' => 'templates/kultuurikava_subevents',
    )
  );
}


/**
 * Get Drupal categories with slugs as key.
 *
 * @return array
 *   categories
 */
function kultuurikava_get_categories($section = 'events') {

  // Default parent category.
  $parent = 0;

  // Get parent category.
  $parent_category = kultuurikava_get_parent_category($section);

  if (isset($parent_category) && !empty($parent_category)) {
    $parent = $parent_category[0];
  }

  $tree = taxonomy_get_tree($vid = 4, $parent, $max_depth = 1, $load_entities = TRUE);
  $categories = array();
  foreach ($tree as $term) {
    if (module_exists('i18n_taxonomy')) {
      $term = i18n_taxonomy_localize_terms($term);
    }

    $slug = $term->field_slug[LANGUAGE_NONE][0]['value'];

    $categories[$slug] = $term->name;
  }

  return $categories;
}


/**
 * Get Parent category.
 *
 * @param string $section
 *   category section. event or activity.
 */
function kultuurikava_get_parent_category($section) {

  // Get parent term id.
  $query = db_select('taxonomy_term_data', 't');
  $query->innerJoin('field_data_field_slug', 's', 't.tid = s.entity_id');
  $query->fields('t', array('tid'));
  $query->condition('t.vid', 4);
  $query->condition('s.bundle', 'categories');
  $query->condition('s.field_slug_value', $section);
  $result = $query->execute()->fetchCol();

  return $result;
}


/**
 * Get internal categories by kultuurikava category id.
 *
 * @param int $category_id
 *   kultuurikava category id
 *
 * @return array
 *   internal categories
 */
function kultuurikava_get_category_by_kk_id($category_id, $section) {

  // Get parent category.
  $parent_category = kultuurikava_get_parent_category($section);
  if (isset($parent_category) && !empty($parent_category)) {
    $parent = $parent_category[0];
  }
  else {
    $parent = 0;
  }

  // Get categories where referencing term id = $category_id
  $query = db_select('taxonomy_term_data', 't');
  $query->innerJoin('field_data_field_kultuurikava_categories', 'kc', 't.tid = kc.entity_id');
  $query->innerJoin('field_data_field_category_id', 'ci', 'kc.field_kultuurikava_categories_tid = ci.entity_id');
  $query->innerJoin('taxonomy_term_hierarchy', 'h', 't.tid = h.tid');
  $query->fields('t', array('name', 'tid'));
  $query->condition('t.vid', 4);
  $query->condition('ci.field_category_id_value', $category_id);
  $query->condition('h.parent', $parent);
  $query->orderBy('t.weight', 'ASC');
  $categories = $query->execute()->fetchAll();

  if ($categories && module_exists('i18n_taxonomy')) {
    foreach ($categories as $key => $category) {
      $term = taxonomy_term_load($category->tid);
      $term = i18n_taxonomy_localize_terms($term);
      $categories[$key]->name = $term->name;
    }
    return $categories;
  }

  return;
}


/**
 * Get kultuurikava slugs by own category slug.
 *
 * @param string $category_slug
 *   own category slug
 *
 * @return array
 *   result
 */
function kultuurikava_get_kk_categories_by_slug($category_slug, $section) {

  // Get parent category.
  $parent_category = kultuurikava_get_parent_category($section);
  if (isset($parent_category) && !empty($parent_category)) {
    $parent = $parent_category[0];
  }
  else {
    $parent = 0;
  }

  $result = array();

  $query = db_select('taxonomy_term_data', 't');
  $query->innerJoin('field_data_field_slug', 's', 't.tid = s.entity_id');
  $query->innerJoin('taxonomy_term_hierarchy', 'h', 't.tid = h.tid');
  $query->fields('t', array('tid', 'name'));
  $query->condition('t.vid', 4);
  $query->condition('s.field_slug_value', $category_slug);
  $query->condition('h.parent', $parent);
  $query->orderBy('t.weight', 'ASC');
  $query->range(0, 1);
  $categories = $query->execute()->fetchAll();

  if ($categories) {

    $term = taxonomy_term_load($categories[0]->tid);
    if (isset($term->field_kultuurikava_categories[LANGUAGE_NONE]) && !empty($term->field_kultuurikava_categories[LANGUAGE_NONE])) {

      foreach ($term->field_kultuurikava_categories[LANGUAGE_NONE] as $reference) {

        $kk_term = taxonomy_term_load($reference['tid']);
        if (isset($kk_term->field_slug[LANGUAGE_NONE]) && !empty($kk_term->field_slug[LANGUAGE_NONE])) {
          foreach ($kk_term->field_slug[LANGUAGE_NONE] as $slug) {
            $result[] = $slug['value'];
          }
        }
      }

    }
  }

  return $result;
}


/**
 * Ticket link.
 *
 * @param array $ticket
 *   ticket array with name, logo, and provider information
 *
 * @return string
 *   rendered link
 */
function kultuurikava_ticket_link($ticket) {
	$base_path = $GLOBALS['base_path'];
	$link_content = $ticket['provider']['name'];
	$link = l($link_content, $ticket['ticketurl'], array('attributes' => array('target' => '_blank')));

  if ($ticket['provider']['logo']) {
    $logo_url = drupal_get_path('theme', 'huvi') . '/images/ticketproviders/' . $ticket['provider']['logo'];

    if(file_exists($logo_url)) {
      $link_content = '<img src="' . $base_path . $logo_url . '" />';
      $link = l($link_content, $ticket['ticketurl'], array('attributes' => array('target' => '_blank'), 'html' => TRUE));
    }
  }

  return $link;
}


/**
 * Make API requests to Kultuurikava and save the events as nodes
 */
function kultuurikava_import_events($limit = 50) {
  // Is the first import done or not
  $first_import_done = variable_get('kultuurikava_import_first_done', FALSE);
  // this increments after each function run for decreasing load on cron and API calls
  $page = variable_get('kultuurikava_import_next_page', 0);
  $last_page = FALSE;

  $start = $page * $limit;
  //$date = date('Y-m-d');
  // Take all events from the start of this year, in case the end time might still be later than today
  $date = date('Y-m-01');
  $parameters = array(
    'do' => 'events',
    'start' => $start,
    'limit' => $limit,
    'group' => 'true',
    'date' => $date,
    'county' => 'tallinn',
    'order' => 'createda', // works and should be used for initial import
    //'order' => 'starta',
    //'recreation' => 'true',
  );

  if($first_import_done) {
    $modified = variable_get('kultuurikava_import_last_time', FALSE);
    if(!$modified) {
      watchdog('kultuurikava', 'kultuurikava_import_last_time variable not set. This should be done automatically in code.', NULL, WATCHDOG_ERROR);
      return;
    }
    $parameters['modified'] = $modified;
    unset($parameters['date']);
  }

  // Get a list of events for IDs at first
  // (note that there are no multiple schedule items in the general calls
  // that's why we need to make individual API calls for each event later)
  $events = kultuurikava_api_call($parameters, NULL, 'nat');

  if (isset($events['events']) && !empty($events['events'])) {
    // Array of event IDs from which to loop and get events by ID
    $event_ids = array();
    foreach($events['events'] as $event_key => $event) {
      // Bypass piletilevi items
      if (!is_piletilevi_item($event)) 
        $event_ids[] = $event['id'];
    }
    $i = 0;
    foreach($event_ids as $event_id_key => $event_id) {
      // Get the specific event node and save it as an event node to Drupal
      kultuurikava_event_data_node_save(kultuurikava_get_event_data($event_id));
      $i++;
    }
    $progress = $start + $i;
    $progress_text = 'Imported/updated ' . $i . ' events. Progress: ' . $progress . '/' . $events['total'];
    watchdog('kultuurikava', $progress_text, NULL, WATCHDOG_INFO);
    variable_set('kultuurikava_import_progress_text', $progress_text);
    // There are more items to import on the next page
    if($events['total'] >= $start + $limit) {
      variable_set('kultuurikava_import_next_page', $page + 1);
    }
    else {
      $last_page = TRUE;
      variable_set('kultuurikava_import_last_time', time());
      if(!$first_import_done) {
        variable_set('kultuurikava_import_first_done', TRUE);
        watchdog('kultuurikava', 'Initial import of all Kultuurikava events is now completed.', NULL, WATCHDOG_INFO);
      }
    }
  }
  else {
    $last_page = TRUE;
    watchdog('kultuurikava', 'Cron ran. Empty events results.', NULL, WATCHDOG_INFO);
    variable_set('kultuurikava_import_progress_text', 'No new events to import');
  }

  // Run this if this is the last page to be imported
  if($last_page) {
    variable_set('kultuurikava_import_next_page', 0);
  }
}

/**
 * Check if provider is Piletilevi
 *
 * @return bool $return
 *   True if provider is Piletilevi
 */
function is_piletilevi_item($event) {
  //check provider
  if (!isset($event['ticketurl']) || empty($event['ticketurl'])) {
    return false;
  }
  if (!isset($event['ticketurl'][0]['provider']['name']) || empty($event['ticketurl'][0]['provider']['name'])) {
    return false;
  }

  $provider_name = strtolower($event['ticketurl'][0]['provider']['name']);
  if (strpos($provider_name, 'piletilevi') !== FALSE) {
    return true;
  }
  else {
    return false;
  }
}

/**
 * Save event from Kultuurikava as a node
 *
 * @return array $return
 *   Event data fields as keys and node fields as values
 */
function kultuurikava_event_to_node_fields() {
  $return = array(
    'id' => 'field_id',
    'name' => 'title',
    'excerpt' => 'field_excerpt',
    'description' => 'field_description',
	'korraldaja' => 'field_korraldaja',
    'hasimage' => 'field_hasimage',
    'image' => 'field_image_url',
    'video' => 'field_video_url',
    'pre_description' => 'field_pre_description',
    'map_latlng' => 'field_map_latlng',
    'map_markers' => 'field_map_markers',
    'type' => 'field_type',
    'ticketurl' => 'field_tickets',
    'schedule' => 'field_schedule',
    'isfree' => 'field_isfree',
    'categories' => 'field_categories_event',
  );
  return $return;
}


/**
 * Get ticket seller names
 *
 * @return array $return
 *   Ticket seller names for getting images
 */
function kultuurikava_get_ticket_seller_name($nr) {
  // TODO: Check that these names correspond to the ones sent from kultuurikava API
  $return = array(
    'Artis' => 1,
    'Cinamon' => 2,
    'Forum Cinemas' => 3,
    'Piletilevi' => 4,
    'Piletimaailm' => 5,
    'solariskino.ee' => 6,
    // www.gateme.com
  );
  if($nr) {
    $return_one = $return[$nr];
    if($return_one) {
      $return = $return_one;
    }
  }
  return $return;
}


/**
 * Get ticket seller image filename
 *
 * @return array $return
 *   Ticket seller logo filenames or just one specific filename
 */
function kultuurikava_get_ticket_seller_image($nr) {
  $return = array(
    'kino.ee' => 'artiskino_logo.jpg',
    'cinamon.ee' => 'cinamon_logo.png',
    'forumcinemas.ee' => 'forumcinemas_logo.jpg',
    'piletilevi.ee' => 'piletilevi_logo.gif',
    'piletimaailm.com' => 'piletimaailm_logo.gif',
    'solariskino.ee' => 'solariskino_logo.jpg',
  );
  if($nr) {
    if(isset($return[$nr])) {
      $return_one = $return[$nr];
      if($return_one) {
        return $return_one;
      }
      return;
    }
    return;
  }
  return $return;
}


/**
 * Get cities from city_id-s from kultuurikava
 *
 * @return array $return
 *   Ticket seller names for getting images
 */
function kultuurikava_city_from_id($city_id) {
  $cities = array(
    2944195 => 'pohja-tallinn',
    2944191 => 'kesklinn',
    2944198 => 'kesklinn', // vanalinn
    2944188 => 'kesklinn', // kadriorg
    2944187 => 'haabersti',
    2944189 => 'kristiine',
    2944190 => 'lasnamae',
    2944193 => 'mustamae',
    2920234 => 'pirita',
    2944194 => 'nomme',
  );
  if($city_id) {
    $city = $cities[$city_id];
    if($city) {
      return $city;
    }
    watchdog('kultuurikava', 'No city found with city_id: ' . $city_id, NULL, WATCHDOG_ERROR);
  }
  else {
    return $cities;
  }
}


/**
 * Get categories based on Kultuurikava category IDs
 *
 * @return array $return
 *   Category IDs to save to drupal
 */
function kultuurikava_event_categories_by_kk_ids($categories, $event_type) {
  /*
  0|Muusika
  1|Etendused
  2|Näitus, muuseum
  3|Mess, laat
  4|Sport
  5|Kino
  6|Pidu, klubid
  7|Lapsele
  8|Varia
  */
  $event = array(
    14453 => 0,
    369755 => 0,
    14452 => 1,
    14455 => 2,
    14465 => 2,
    14459 => 3,
    14456 => 4,
    14454 => 5,
    14457 => 6,
    160542 => 6,
    14458 => 7,
    5218297 => 8,
    5218295 => 8,
    14460 => 8,
    5218296 => 8,
    14463 => 8,
    14461 => 8,
    14462 => 8,
    14466 => 8,
    14464 => 8,
  );

  /*
  0|Muusika
  1|Kunst, käsitöö
  2|Tantsimine
  3|Sport, liikumine
  4|Tehnika
  5|Keeleõpe
  6|Koolitused, kursused
  7|Lapsele
  8|Varia
  */
  $activity = array(
    14453 => 0,
    5218295 => 1,
    369755 => 2,
    14456 => 3,
    5218296 => 4,
    5218297 => 5,
    160542 => 6,
    14458 => 7,
    14460 => 8,
    14452 => 8,
    14455 => 8,
    14465 => 8,
    14459 => 8,
    14454 => 8,
    14457 => 8,
    14463 => 8,
    14461 => 8,
    14462 => 8,
    14466 => 8,
    14464 => 8,
  );

  if($categories) {
    $list = $event;
    if($event_type == 'huvitegevus') {
      $list = $activity;
    }
    $return = array();
    foreach($categories as $key => $kk_id) {
      $return[] = $list[$kk_id];
    }
    return $return;
  }
  else {
    watchdog('kultuurikava', 'Category was empty to get event category listing', NULL, WATCHDOG_ERROR);
    return;
  }
}


/**
 * Save event from Kultuurikava as a node
 *
 * @param array $event_id
 *   Event ID of the Kultuurikava event
 */
function kultuurikava_event_data_node_save($event) {
  if(!$event) {
    watchdog('kultuurikava', "No event data found in function kultuurikava_event_data_node_save", NULL, WATCHDOG_ERROR);
    return;
  }
  $e = $event;

  // Check if the node exists already
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->fieldCondition('field_id', 'value', $e['id'], '=')
    ->execute();
  // Node exists, load the entity
  if($result) {
    foreach($result['node'] as $key => $val) {
      $entity_load = entity_load('node', array($key));
      foreach($entity_load as $ekey => $eval) {
        $entity = $eval;
      }
    }
  }
  // Node doesn't exist yet, create a new entity
  else {
    $values = array(
      'type' => 'event',
      'uid' => 1,
      'status' => 1,
      'comment' => 0,
      'promote' => 0,
      'language' => 'et',
    );
    $entity = entity_create('node', $values);
  }

  $w = entity_metadata_wrapper('node', $entity);
  $fields = kultuurikava_event_to_node_fields();
  foreach($fields as $event_item => $field) {
    if(isset($e[$event_item])) {
      switch($event_item) {
        case 'schedule':
          // Get and remove all the existing field collection items and save them again (because there might be changes)

          if(!empty($entity->field_schedule['und'])) {
            $s_values = array();
            foreach($entity->field_schedule['und'] as $s_key => $s_val) {
              $s_values[] = $s_val['value'];
              unset($entity->field_schedule['und'][$s_key]);
            }
            if(!empty($s_values)) {
              entity_delete_multiple('field_collection_item', $s_values);
            }
          }
          foreach($e['schedule'] as $key => $val) {
            $schedule_item = entity_create('field_collection_item', array('field_name' => 'field_schedule'));
            $schedule_item->setHostEntity('entity', $entity);
            $schedule_wrapper = entity_metadata_wrapper('field_collection_item', $schedule_item);

            if($val['start_time'] && is_int($val['start_time'])) {
              if(is_int($val['end_time']) && $val['end_time'] < 2000000000) {
                $schedule_wrapper->field_schedule_date[0]->set(array(
                  'value' => $val['start_time'],
                  'value2' => $val['end_time'],
                ));
              }
              else {
                $schedule_wrapper->field_schedule_date[0]->set(array(
                  'value' => $val['start_time'],
                ));
              }
            }
            if($val['city_id'] == '2944198' || $val['city_id'] == '2944188') {
              $val['city_id'] = 2944191;
            }
            $schedule_wrapper->field_schedule_place->set($val['place']);
            $schedule_wrapper->field_schedule_city_id->set($val['city_id']);
          }
          break;
        case 'ticketurl':
          $ticket_urls = array();
          foreach($e[$event_item] as $key => $val) {
            $ticket_urls[] = $val['ticketurl'];
          }
          if(!empty($ticket_urls)) {
            $w->{$field}->set($ticket_urls);
          }
          break;
        case 'categories':
          $field_name = 'field_categories_event';
          if($e['type'] == 'huvitegevus') {
            $field_name = 'field_categories_activity';
          }
          $categories = array();
          foreach($e[$event_item] as $category_id) {
            $categories = kultuurikava_event_categories_by_kk_ids($e[$event_item], $e['type']);
          }
          if(!empty($categories)) {
            $w->{$field_name}->set($categories);
          }
          break;
        case 'description':
          $w->{$field}->value->set($e[$event_item]);
          break;
        case 'type':
          $w->{$field}->set($e[$event_item]);
          break;
        default:
          $w->{$field}->set($e[$event_item]);
          break;
      }
    }
  }
  $w->field_source->set(3);
  $w->save();
}


/**
 * Convert node to proper event fields displayed on the event node template page
 *
 * @param object $node
 *   Event node to be converted to the event array
 *
 * @return array $e
 *   Event data for showing in the event template on the node page
 */
function kultuurikava_node_to_event($node) {
  $n = $node;
  $e = array();
  $addedMarkers = array();
  $fields = kultuurikava_event_to_node_fields();

  // If the event has sub-events set
 /* $sub_event_ids = kultuurikava_get_sub_event_ids($n->nid);
  if(isset($sub_event_ids)) {
    $sub_events = array();
    foreach($sub_event_ids as $sub_event_id) {
      $sub_event = kultuurikava_get_sub_event($sub_event_id);
      if(isset($sub_event) && is_array($sub_event)) {
        foreach ($sub_event as $s) {
          $sub_events[] = $s;
        }
      }
    }
    if(isset($sub_events)) {
      $sub_events = _kultuurikava_rearrange_sub_events($sub_events);
      //_kultuurikava_group_sub_events($sub_events);
      $e['sub_events'] = _kultuurikava_group_sub_events($sub_events);
    }
  }*/

  // If the event has a main event set
  if(isset($n->field_main_event_ref['und'][0]['node'])) {
    $main_node = $n->field_main_event_ref['und'][0]['node'];
    if($main_node->status == '1') {
      $e['main_event'] = array(
        'title' => $main_node->title,
        'path' => url('node/' . $main_node->nid),
      );
    }
  }

  foreach($fields as $event => $field) {
    switch($event) {
      case 'name':
        $e[$event] = $n->{$field};
        break;

		case 'korraldaja'://Korraldaja fields
		if(isset($n->{$field}['und'])) {
			foreach($n->{$field}['und'] as $key => $val) {
					if (isset($val['value'])) {
					$collections = entity_load('field_collection_item', array($val['value']));

						foreach($collections as $c) {
							if(isset($c->field_korraldaja_nimi['und'])) {
								foreach($c->field_korraldaja_nimi['und'] as $korraldaja_key => $nimi) {
									if(isset($nimi['value'])) {
									$korraldaja_nimi= $nimi['value'];
									$e[$event][$korraldaja_key]["name"] = $korraldaja_nimi;
									}
								}
							}
							if(isset($c->field_korraldaja_kontakttelefon['und'])) {
								foreach($c->field_korraldaja_kontakttelefon['und'] as $korraldaja_key => $kontakttelefon) {
									if(isset($kontakttelefon['value'])) {
									$korraldaja_kontakttelefon= $kontakttelefon['value'];
									$e[$event][$korraldaja_key]["phone"] = $korraldaja_kontakttelefon;
									}
								}
							}

							if(isset($c->field_korraldaja_e_post['und'])) {
								foreach($c->field_korraldaja_e_post['und'] as $korraldaja_key => $e_post) {
									if(isset($e_post['email'])) {
									$korraldaja_e_post= $e_post['email'];
									$e[$event][$korraldaja_key]["email"] = $korraldaja_e_post;
									}
								}
							}

						}


					}
			}
		}
        break;

      case 'schedule':
        if(isset($n->{$field}['und'])) {
          $event_key = 0;

          foreach($n->{$field}['und'] as $key => $val) {
           if (isset($val['value'])) {

            $collections = entity_load('field_collection_item', array($val['value']));

            foreach($collections as $c) {

              if(isset($c->field_schedule_date['und'])) {
                foreach($c->field_schedule_date['und'] as $time_key => $time) {

                  if(isset($time['value'])) {
                    if ($time['value'] < time()) continue;
                    $start_date = $time['value'];
                    $end_date = (isset($time['value2'])) ? $time['value2'] : '';
                    $e[$event][$event_key]['asort'] = $start_date;
                    $e[$event][$event_key]['time'] = kultuurikava_date_format_2($start_date, $end_date);
                    if(!empty($c->field_schedule_toimumis)){
                      $toimumiskoht = $c->field_schedule_toimumis['und'][0]['taxonomy_term']->name;
                    }
                    if(!empty($c->field_schedule_place)){
                      $place = $c->field_schedule_place['und'][0]['value'];
                    }
                    if(!empty($toimumiskoht)){
                      $e[$event][$event_key]['place'] = $toimumiskoht;
                      if(!empty($place))
                       $e[$event][$event_key]['place'] = ' <span class="event-place-toimumiskoht">'.$toimumiskoht .'</span><br>'. $place;
                    }
                    else{
                      $e[$event][$event_key]['place'] = isset($place) ? $place : '';
                    }

                    $event_key++;
                  }
                }
              }

              // Read manually inserted markers only when no imported ones were detected
              if(isset($c->field_schedule_location['und'][0]['lat']) && isset($c->field_schedule_location['und'][0]['lng'])) {
                $marker = $c->field_schedule_location['und'][0]['lat'] . ',' . $c->field_schedule_location['und'][0]['lng'];
                if(!isset($e['map_latlng'])) {
                  $addedMarkers['map_latlng'] = $marker;
                }
                if(isset($addedMarkers['map_markers'])) {
                  $addedMarkers['map_markers'] .= ';' . $marker;
                }
                else {
                  $addedMarkers['map_markers'] = $marker;
                }
              }
            }
          }
         }
        }
        break;
      case 'ticketurl':
        if(isset($n->{$field}['und'])) {
          foreach($n->{$field}['und'] as $key => $url) {
            $url_parse = parse_url($url['value']);
            if(!isset($url_parse['host'])) {
              $url_parse = explode('/', $url_parse['path']);
              $url_host = $url_parse[0];
              $url['value'] = 'http://' . $url['value'];

            }
            else {
              $url_host = $url_parse['host'];
            }
            if (substr($url_host, 0, strlen('www.')) == 'www.') {
              $url_host = substr($url_host, strlen('www.'));
            }
            $link_content = $url_host;
            $logo_filename = kultuurikava_get_ticket_seller_image($url_host);
            if(!empty($logo_filename)) {
			  $base_path = $GLOBALS['base_path'];
              $logo_url = drupal_get_path('theme', 'huvi') . '/images/ticketproviders/img/' . $logo_filename;
              if(file_exists($logo_url)) {
                $link_content = '<img src="' . $base_path . $logo_url . '" alt="' . $url_host . '" />';
              }
            }
            $t_link = l($link_content, $url['value'], array('attributes' => array('target' => '_blank'), 'html' => TRUE));
            $e[$event][$key] = $t_link;
          }
        }
        break;
      default:
        if(isset($n->{$field}['und'])) {
          if(isset($n->{$field}['und'][0]['value'])) {
            $e[$event] = $n->{$field}['und'][0]['value'];
          }
        }
        break;
    }
  }
  // If no markers are imported (most probably event was added manually),
  // then add the manually added markers if they exist
  if(!isset($e['map_markers']) && isset($addedMarkers['map_markers'])) {
    $e['map_markers'] = $addedMarkers['map_markers'];
    $e['map_latlng'] = $addedMarkers['map_latlng'];
  }

  return $e;
}


/**
 * Get sub events by node ID
 *
 * @param object $node_id
 *   Event node ID of which to get sub events from
 *
 * @return array $sub_events
 *   Sub events data
 */
function kultuurikava_get_sub_event_ids($node_id) {
  // Get parent term id.
  $query = db_select('field_data_field_main_event_ref', 'f');
  $query->fields('f', array('entity_id'));
  $query->condition('f.field_main_event_ref_nid', $node_id);
  $results = $query->execute()->fetchAll();
  $sub_event_ids = array();
  if($results) {
    foreach($results as $result) {
      $sub_event_ids[] = $result->entity_id;
    }
    return $sub_event_ids;
  }
  return;
}


/**
 * Get sub events by node ID
 *
 * @param object $node_id
 *   Event node ID of which to get the sub event data
 *
 * @return array $sub_events
 *   Data usable for event node view
 */
function kultuurikava_get_sub_event($node_id, $active_filters=array()) {
  // Get parent term id.
  $node = node_load($node_id);
  // Static variables for filters handler
   $existing_event_types =  &drupal_static('kultuurikava_existing_events_types');
   $existing_districts =  &drupal_static('kultuurikava_existing_districts');
   $existing_dates =  &drupal_static('kultuurikava_existing_dates');
   $current_event_types = array();
  // Use only published nodes
  if($node->status == '1') {
    $return = array();
    if(isset($node->field_schedule['und'])) {
      $event_type = field_get_items('node', $node, 'field_type');
      $event_type = reset($event_type);

      if ($event_type['value'] == 'uritus') {
        $event_category = field_get_items('node', $node, 'field_categories_event');
      }
      else{
        $event_category = field_get_items('node', $node, 'field_categories_activity');
      }

      foreach($node->field_schedule['und'] as $key => $val) {

        $tmp_data = array();

        if (isset($val['value'])) {

          $collections = entity_load('field_collection_item', array($val['value']));

          foreach($collections as $c) {

            if(isset($c->field_schedule_date['und'])) {
              foreach($c->field_schedule_date['und'] as $time_key => $time) {

                $tmp_time = '';
                if(isset($time['value'])) {
                  if ($time['value'] < time()) continue;
                  _kultuurikava_get_relative_date_filters($time['value']);
                  $start_date = $time['value'];
                  // Apply date filter
                  if (isset($active_filters['date']) && !empty($active_filters['date'])){
                    $period_start_date =  null;
                    $period_end_date = null;
                    if(($active_filters['date'][0]=='period') && isset($active_filters['period'])) {
                      $period_start_date = strtotime($active_filters['period']['start_date']);
                      $period_end_date = strtotime($active_filters['period']['end_date']);
                    }
                    if(_kultuurikava_check_date_filters($time['value'], $active_filters['date'][0], $period_start_date, $period_end_date) == FALSE) {
                      continue;
                    }
                  }
                  $end_date = (isset($time['value2'])) ? $time['value2'] : '';
                  $tmp_time = kultuurikava_date_format_2($start_date, $end_date, TRUE);
                  // Apply linnaosa filter
                  $existing_districts[] = $c->field_schedule_city_id['und'][0]['value'];
                  if (isset($active_filters['district'])
                      && !empty($active_filters['district'])
                      && !in_array($c->field_schedule_city_id['und'][0]['value'], $active_filters['district']) ) {
                    continue;
                  }
                  //// Apply tüüp filter
                  if (is_array($event_category)) {
                    foreach ($event_category as $value) {
                      $existing_event_types[] = ($event_type['value'] == 'uritus')? 'ev_' . $value['value'] : 'act_' . $value['value'];
                      $current_event_types[] = ($event_type['value'] == 'uritus')? 'ev_' . $value['value'] : 'act_' . $value['value'];
                    }
                  }
                  if(isset($active_filters['type']) && !empty($active_filters['type'])) {
                    if (array_intersect($active_filters['type'], $current_event_types) == array()) continue;
                  }
                  $toimumiskoht = '';
                  if (isset($c->field_schedule_toimumis['und'])) {
                    $toimumiskoht = taxonomy_term_load($c->field_schedule_toimumis['und'][0]['tid'])->name;
                  }
                  $place = $c->field_schedule_place['und'][0]['value'];
                  $tmp_place = '';
                  if(!empty($toimumiskoht)) {
                    $tmp_place = $toimumiskoht;
                  }
                  if(!empty($place)) {
                    $place =  preg_replace('/, ?(Eesti|Estonia)$/', '', $place);
                    $place =  preg_replace('/, ?\d* ?Tallinn$/', '', $place);
                    if (!empty($tmp_place) && !empty($place)){
                      $tmp_place .=  ', ' . $place;
                    }
                    else {
                      $tmp_place = $place;
                    }
                  }
                  $return[] = array(
                    'title' => $node->title,
                    'path' => url('node/' . $node->nid),
                    'timestamp' => $time['value'],
                    'time' => $tmp_time,
                    'place' => $tmp_place,
                  );
                }
              }
            }
          }
        }
      }
    }

    /*if (count($return) == 0) {
      $return[] = array(
        'title' => $node->title,
        'path' => url('node/' . $node->nid),
	'timestamp' => null,
        'time' => '',
        'place' => '',
      );
    }*/

    return $return;
  }
  return;
}


/**
 * Manually execute cron function for importing events from Kultuurikava API
 */
function kultuurikava_manual_import() {
  kultuurikava_cron();
  print t('Importing kultuurikava items...') . '<br>';
  print variable_get('kultuurikava_import_progress_text', 'updating status.') . '<br>';
  if(variable_get('kultuurikava_import_first_done') == TRUE) {
    print t('Refreshing automatically after every 3 minutes.') . '<br>';
    header("Refresh: 180;");
  }
  else {
    print t('Refreshing automatically after every 2 seconds.') . '<br>';
    header("Refresh: 2;");
  }
}


/* Helper functions */

/**
 * Function for date formating
 */
function kultuurikava_date_format ($start_date, $end_date) {
  $date_format = 'D, d.m.Y H:i';
  $short_date_format = 'D, d.m.Y';

  if(isset($end_date)) {
  // No need to show the ending date, when it's the same as the starting date
    if($start_date == $end_date) {
      if (date('H:i', $start_date) == '00:00')
       $date =  format_date($start_date, 'custom', $short_date_format) . ' ' . t('Kogu päev');
      else
        $date = format_date($start_date, 'custom', $date_format);
      }
    else {
      if (date('H:i', $start_date) == '00:00') {
        $date = format_date($start_date, 'custom', $short_date_format)
                . ' - '
                . format_date($end_date, 'custom', $short_date_format);
       }
       else {
         $date = format_date($start_date, 'custom', $date_format)
                . ' - '
                . format_date($end_date, 'custom', $date_format);
       }
      }
    }
    else {
      if (date('H:i', $start_date) == '00:00')
        $date =  format_date($start_date, 'custom', $short_date_format) . ' ' . t('Kogu päev');
      else
        $date =  format_date($start_date, 'custom', $date_format);
      }
  return $date;
}


/**
 * Another function for date formating
 */
function kultuurikava_date_format_2($start_date, $end_date = '', $only_time = FALSE) {
  $date_format = 'D, d.m.y';
  $date_format_time = 'H:i';

  if ($only_time) {
    $start_date_n_time =   format_date($start_date, 'custom', $date_format_time);
  }
  else {
    $start_date_formatted = format_date($start_date, 'custom', $date_format);
    $start_time_formatted = format_date($start_date, 'custom', $date_format_time);
    $start_date_n_time = t('!s_date kell !s_time', array(
    '!s_date' => $start_date_formatted,
    '!s_time' => $start_time_formatted,
   ));
  }


  $end_date_n_time = '';

  if ($end_date != '' && $start_date != $end_date) {
    if ($only_time) {
       $end_date_n_time = ' - ' . format_date($end_date, 'custom', $date_format_time);
    }
    else {
      $end_date_formatted = format_date($end_date, 'custom', $date_format);
      $end_time_formatted = format_date($end_date, 'custom', $date_format_time);
      $end_date_n_time = ' - ' . t('!s_date kell !s_time', array(
      '!s_date' => $end_date_formatted,
      '!s_time' => $end_time_formatted,
    ));
    }
  }

  return (date('H:i', $start_date) == '23:55')
    ? ($start_date_formatted . ' ' . t('Kogu päev'))
    : ($start_date_n_time . $end_date_n_time);
}



function _kultuurikava_rearrange_sub_events(&$arr) {
  $tmp_arr1 = array();
  $tmp_arr2 = array();

  foreach ($arr as $a) {
    if ($a['timestamp'] == null) $tmp_arr2[] = $a;
    else $tmp_arr1[] = $a;
  }

  usort($tmp_arr1, '_kultuurikava_sort_by_timestamp');
  $result = array_merge($tmp_arr1, $tmp_arr2);

  return $result;
}


function _kultuurikava_sort_by_timestamp($a, $b) {
  return $a['timestamp'] - $b['timestamp'];
}

function _kultuurikava_group_sub_events($arr) {
  $sub_events = array();
  foreach ($arr as $key => $sub_event) {
   $sub_events[date("Ymd", $sub_event["timestamp"])][] = $sub_event;
  }
  return $sub_events;
}

/**
 * Implements hook_block_info().
 */
function kultuurikava_block_info() {
  $blocks = array();
  $blocks['kultuurikava_sub_events_block'] = array(
    'info' => t('Subevents'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function kultuurikava_block_view($delta='', $nid=null) {
  $block = array();
  switch($delta) {
    case 'kultuurikava_sub_events_block' :
      if (isset($nid)) {
        $filters = array();
        $active_filters = array('date' => array('all'));

        $node = node_load($nid);
        $show_filters = field_get_items('node', $node, 'field_subevents_filter');
         $existing_dates =  &drupal_static('kultuurikava_existing_dates');
         $existing_dates = array('all', 'period');
        if ($show_filters && $show_filters[0]['value'] == 1) {
          $event_type = field_get_items('node', $node, 'field_type');
          $event_type = reset($event_type);
          $filters = kultuurikava_get_filters($event_type['value']);
        }
        $sub_events = kultuurikava_get_subevents($nid, $active_filters);
        $existing_districts = &drupal_static('kultuurikava_existing_districts');
        $existing_event_types =  &drupal_static('kultuurikava_existing_events_types');
        if(is_array($existing_event_types)){
          $existing_event_types = array_unique($existing_event_types);
        }
        $existing_event_types = _kultuurikava_mapping_filters_to_event_categories($existing_event_types);
        if(is_array($existing_districts)){
          $existing_districts = array_unique($existing_districts);
        }
        $existing_dates = array_unique($existing_dates);
        if (count($existing_districts) == 1){
          unset($filters['district']);
        }
        if (count($existing_event_types ) == 1){
          unset($filters['type']);
        }
        $existing_filters = array ('district' => $existing_districts, 'type' => $existing_event_types , 'date' => $existing_dates);
        $block['content'] = theme('kultuurikava_subevents_block', array('parent_nid' => $nid,
          'subevents' => $sub_events,
          'filters' => $filters,
          'existing_filters' => $existing_filters,
          'active_filters'=> $active_filters)
        );
      }


      break;
  }

  return $block;
}
/*
 * Helper function
 * @return subevents for node
 */
function kultuurikava_get_subevents($nid, $active_filters = array()) {
  $sub_event_ids = kultuurikava_get_sub_event_ids($nid);
  if(isset($sub_event_ids)) {
    $sub_events = array();
    foreach($sub_event_ids as $sub_event_id) {
      $sub_event = kultuurikava_get_sub_event($sub_event_id, $active_filters);
      if(isset($sub_event) && is_array($sub_event)) {
        foreach ($sub_event as $s) {
          $sub_events[] = $s;
        }
      }
    }
    if(isset($sub_events)) {
      $sub_events = _kultuurikava_rearrange_sub_events($sub_events);
      $sub_events = _kultuurikava_group_sub_events($sub_events);

     return $sub_events;
    }
  }
}
/*
 * Helper function to recieve filters
 */
function kultuurikava_get_filters ($event_type) {
  $filters = array (
    'date' => array (
      'label' => t('Kõik toimimusajad'),
        'tabs' => array (
        'all' => t('Kõik toimimusajad'),
        'today' => t('Täna'),
        'tomorrow' => ('Homme'),
        'fs' => t('R-P'),
        'month' => t('Sel kuul'),
        'period' => t('Vali ajavahemik')
      )
    ),

    'district' => array (
      'label' => t('Kõik linnaosad'),
      'tabs' => array(
        2944195 => 'Põhja-Tallinn',
        2944191 => 'Kesklinn',
        2944187 => 'Haabersti',
        2944189 => 'Kristiine',
        2944190 => 'Lasnamäe',
        2944193 => 'Mustamäe',
        2920234 => 'Pirita',
        2944194 => 'Nõmme',
      )
    ),
    'type' => array (
      'label' => t('Kõik ürituse tüübid'),
      'tabs' => array(
        'muusika' => t('Muusika'),
        'etendus' => t('Etendused'),
        'muuseum' => t('Näitus, muuseum'),
        'laat' => t('Mess, laat'),
        'sport' => t('Sport'),
        'kino' => t('Kino'),
        'klub' => t('Pidu, klubid'),
        'lapsed' => t('Lapsele'),
        'varia' => t('Varia'),
        'kunst' => t('Kunst, käsitöö'),
        'tants' => t('Tantsimine'),
        'sport' => t('Sport, liikumine'),
        'tehn' => t('Tehnika'),
        'keel' => t('Keeleõpe'),
        'kursused' => t('Koolitused, kursused')
       )
      ));

  return $filters;
}

/*
 * Helper function.
 * Return filters array based on catregories array
 *
 */
function _kultuurikava_mapping_event_categories_to_filters($categories){
  $filters =  array();
  $event_categories =array(
    'muusika' => array('ev_0', 'act_0'),
    'etendus' => array('ev_1'),
    'muuseum' => array('ev_2'),
    'laat' => array('ev_3'),
    'sport' => array('ev_4', 'act_3'),
    'kino' => array('ev_5'),
    'klub' => array('ev_6'),
    'lapsed' => array('ev_7', 'act_7'),
    'varia' => array('ev_8', 'act_8'),
    'kunst' => array( 'act_1'),
    'tants' => array('act_2'),
    'sport' => array('act_3'),
    'tehn' => array('act_4'),
    'keel' => array( 'act_5'),
    'kursused' => array('act_6'),
  );
   foreach($categories as $category){
     $filters = array_merge($filters, $event_categories[$category]);
   }
   return  $filters;
}
/*
 * Helper function.
 * Return categories array based on filters array
 *
 */
function _kultuurikava_mapping_filters_to_event_categories($filters) {
  $categories =  array();
  $filters_array =  array(
    'act_0' => 'muusika',
    'act_1' => 'kunst',
    'act_2' => 'tants',
    'act_3' => 'sport',
    'act_4' => 'tehn',
    'act_5' => 'keel',
    'act_6' => 'kursused',
    'act_7' => 'lapsed',
    'act_8' => 'varia',
    'ev_0' => 'muusika',
    'ev_1' => 'etendus',
    'ev_2' => 'muuseum',
    'ev_3' => 'laat',
    'ev_4' => 'sport',
    'ev_5' => 'kino',
    'ev_6' => 'klub',
    'ev_7' => 'lapsed',
    'ev_8' => 'varia',
  );
  foreach ((array) $filters as $filter) {
    $categories[] = $filters_array[$filter];
  }
  return $categories;
}

/*
 * Helper function. Return date filters.
 */

function _kultuurikava_get_relative_date_filters($timestamp){
  $existing_dates =  &drupal_static('kultuurikava_existing_dates');

  if ($timestamp < strtotime('tomorrow')) {
     $existing_dates[] = 'today';
  }
  if($timestamp > strtotime('tomorrow') && $timestamp < strtotime('tomorrow + 1 day')) {
     $existing_dates[] = 'tomorrow';
  }
  if($timestamp > strtotime('Friday this week') && $timestamp < strtotime('Monday next week')) {
     $existing_dates[] = 'fs';
  }
  if ($timestamp < strtotime('last day of this month')) {
     $existing_dates[] = 'month';
  }
}

function _kultuurikava_check_date_filters($timestamp, $filter, $start_date=null, $end_date=null){
  switch ($filter) {
    case 'all':
      return TRUE;
    case 'today' :
      $start_date = time();
      $end_date = strtotime('tomorrow');
      break;
    case 'tomorrow':
      $start_date = strtotime('tomorrow');
      $end_date = strtotime('tomorrow + 1 day');
      break;
    case 'fs' :
      $start_date = strtotime('Friday this week');
      $end_date = strtotime('Monday next week');
      break;
    case 'month' :
      $start_date = time();
      $end_date = strtotime('last day of this month');
      break;
  }
  if($timestamp > $start_date && $timestamp < $end_date) {
    return TRUE;
  }

  return FALSE;
}