<?php
/**
 * @file
 * Code for the clone_of_event_listing_feature feature.
 */

include_once 'event_listing_fixed_feature.features.inc';

function huvi_views_pre_render(&$view) {
  // Scramble the order of the rows shown on this result page.
  // Note that this could be done earlier, but not later in the view execution
  // process.
 // krumo($view);
  if ($view->name == 'event_listing_fixed'){
		$count=count($view->result);
		
	for ($i = 0; $i <$count; $i++) {
			
		$toimumiskoht=$view->result[$i]->field_field_schedule_toimumiskoht[0]['rendered']['#markup'];
		$place=$view->result[$i]->field_field_schedule_place[0]['rendered']['#markup'];
		
		if(isset($toimumiskoht)){
		
			$place= $toimumiskoht . ', ' . $place;
			$explode = (explode(",",$place, -1));//The explode() function breaks a string into an array.
			$place=$explode[0].",".$explode[1];
			
			}
			
			else{	
			
				$koht= (explode(" ",$place, -1));//The explode() function breaks a string into an array.
				$placeTemp="";
				$coun=count($koht);
				
				for ($j = 1; $j <$coun; $j++){
					
					if(!empty($placeTemp)){
						
						$placeTemp = $placeTemp." ".$koht[$j-1];
						
					}
					else{
						
						$placeTemp = $placeTemp.$koht[$j-1];
					}
					
					if (preg_match("/^[0-9]{5,5}$/",$koht[$j])){//check index
						$j = $coun;
					}
				}
				// delete ','
				if(substr($placeTemp,-1) == ','){
					$place=substr($placeTemp,0,-1);
				}else{
					$place=$placeTemp;
				}
				
				
			}
			
			
	$view->result[$i]->field_field_schedule_place[0]['rendered']['#markup']=$place;
	$view->result[$i]->field_field_schedule_toimumiskoht[0]['rendered']['#markup']="";
	
	}
			
}
	return $view;
}

