name = Kuhuminna Single
description = 2 column layout used on single event pages
preview = preview.png
template = single-layout

; ========================================
; Regions
; ========================================
regions[top_bar_left] = Top bar left
regions[top_bar_right] = Top bar right
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer] = Footer
regions[footer_logo] = Footer Logo
regions[footer_copyright] = Footer Copyright
regions[footer_main_first] = Footer Main First
regions[footer_main_second] = Footer Main Second
regions[footer_main_third] = Footer Main Third
regions[footer_main_fourth] = Footer Main Fourth

; Stylesheets
stylesheets[all][] = css/layouts/single/single.layout.css
