<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function huvi_piletilev_json_import_menu() {
  $items = array();

  // Route admin/config/services/piletilev for setting
  $items['admin/config/services/piletilev'] = array(
    'title' => 'Piletilevi Integration settings',
    'description' => 'Global settings piletilevi Integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('huvi_piletilev_json_import_settings_form'),
    'file' => 'huvi_piletilev_json_import.admin.inc',
    'access arguments' => array('Administrator configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  // Route piletilevi/test for module test
  $items['piletilevi/import'] = array(
    'title' => 'Piletilevi import route',
    'description' => 'Piletilevi import route for feed check',
    'page callback' => 'getFeed',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_cron().
 */
function huvi_piletilev_json_import_cron() {
  getFeed();
}

/**
 * getFedd()
 * This function will connect to Piletilevi JSON Feed and read it to use internally.
 */
function getFeed() {

  // Get API url from setting
  $json_url = variable_get('huvi_piletilev_json_url', '');

  // Fetch data from feed
  $data = @file_get_contents($json_url);
  // Push data as JSON.
  $decodedData = json_decode($data);

  $concerts = is_array($decodedData->responseData->concert) ? (array)$decodedData->responseData->concert : [];
  $events = is_array($decodedData->responseData->venue) ? (array)$decodedData->responseData->venue : [];
  $organizers = (isset($decodedData->responseData->promoter) && is_array($decodedData->responseData->promoter)) ? (array)$decodedData->responseData->promoter: [];
  $shows = is_array($decodedData->responseData->show) ? (array)$decodedData->responseData->show : [];

  // Store reformatted data from Piletilevi feed. 
  $response = [];

  // Items counter.
  $counter = 0;

  foreach ($concerts as $value) {
    $response[$counter]['category'] = [];
    $cats = [];
    foreach ($shows as $show) {
      if ($value->showId == $show->id) {
        foreach ($show->categories as $catid) {
          $cats = catMapping($catid, $cats);
        }
      }
    }
    if ((count($cats) != 0) && isset($value->id)) {
      // Reformat and fill data.
      $response[$counter]['category'] = $cats;
      $response[$counter]['pui'] = $value->id;
      $response[$counter]['title'] = $value->decoratedTitle;
      $response[$counter]['body'] = $value->description;
      $start = $value->startTime->year . '-' . $value->startTime->month . '-' . $value->startTime->date . 'T' . $value->startTime->time . ':00';
      $end = $value->endTime->year . '-' . $value->endTime->month . '-' . $value->endTime->date . 'T' . $value->endTime->time . ':00';
      $response[$counter]['startTime'] = $start;
      $response[$counter]['endTime'] = $end;
      $response[$counter]['moreInfoLink'] = $value->link;
      // Prices
      $prices = explode("-", $value->prices);
      $minPrice = array_key_exists(0, $prices) ? trim($prices[0]) : null;
      $maxPrice = array_key_exists(1, $prices) ? trim($prices[1]) : null;
      $response[$counter]['imageURL'] = $value->imageUrl;
      $response[$counter]['priceType'] = 'range';
      $response[$counter]['minPrice'] = $minPrice;
      $response[$counter]['maxPrice'] = $maxPrice;
      $response[$counter]['buyLink'] = $value->buyButtonConfig->url;
      $response[$counter]['ticketAvailability'] = 'link';

      // Find location information.
      foreach ($events as $event) {
        if ($value->venueId == $event->id) {
          $response[$counter]['eventAddress'] = $event->address;
          $response[$counter]['eventLocation'] = $event->decoratedTitle;
          $geo = $pieces = explode(",", $event->coordinates);
          $response[$counter]['eventLat'] = array_key_exists(0, $geo) ? trim($geo[0]) : null;
          $response[$counter]['eventLng'] = array_key_exists(1, $geo) ? trim($geo[1]) : null;
        }
      }

      // Find orginizers information.
      foreach ($organizers as $organizer) {
        if ($value->promoterId == $organizer->id) {
          $response[$counter]['organizerCompany'] = $organizer->title;
          $response[$counter]['organizerAddress'] = $organizer->address;
          $response[$counter]['organizerURL'] = $organizer->url;
          $response[$counter]['organizerPhone'] = $organizer->phone;
          $response[$counter]['organizerEmail'] = $organizer->email;
        }
      }

      saveEvent($response[$counter]);
      // Next item
      $counter++;
    }
  }
}

/**
 * catMapping()
 * This function will return array of categories.
 * 
 */
function catMapping($catId, $cats) {
  // Mapping teater categories IDs from Piletilev. 

  /*
    Cat list
    0 => Muusika
    1 => Etendused
    2 => Näitus, muuseum
    3 => Mess, laat
    4 => Sport
    5 => Kino
    6 => Pidu, klubid
    7 => Lapsele
    8 => Varia
   */

  $map = array(
    0 => [
      1372, 1349, 1332,
      1231, 1094, 1016,
      1451, 1286, 1451,
      1032, 1348, 1144,
      1002, 1363, 1251,
      1031, 1014, 1323,
      1299, 1112, 1017,
      1106, 1287, 1324,
      1207, 1350, 1243,
      1071, 1058, 1006,
      1394
    ],
    1 => [
      1035, 1256, 1168,
      1289, 1290, 1013,
      1030, 1015, 1054,
      1037, 1261, 1021,
      1419, 1319, 1020,
      1029, 1062, 1129,
      1006, 1394, 1019,
      1022,
      1003, 1291, 1195, // Teaters
      1114
    ],
    2 => [
      1230, 1317, 1028
    ],
    3 => [
      1038
    ],
    4 => [
      1333, 1055, 1005,
      1076, 1065, 1427,
      1024
    ],
    5 => [
      1391, 1056, 1202,
      1161, 1298, 1006,
      1394
    ],
    6 => [
      1220, 1153, 1033,
      1010, 1071, 1006,
      1394
    ],
    7 => [
      1224, 1021, 1004,
      1396, 1058
    ],
    8 => [
      1364, 1075, 1300,
      1383, 1341, 1284,
      1301, 1004, 1396,
      1071, 1058, 1322,
      1280, 1315
    ]
  );

  foreach ($map as $key => $value) {
    if (in_array($catId, $value)) {
      if (!in_array($catId, $cats)) {
        $cats[] = $key;
      }
    }
  }

  return $cats;
}

/**
 * saveEvent()
 * This function will create/update node.
 * 
 * @param $nodeData
 *    Node data as array.
 */
function saveEvent($nodeData) {

  global $user;

  if (checkIfNodeExist($nodeData['pui'])) {
    $entity = loadNodeByPUI($nodeData['pui']);
  }
  else {
// entity_create replaces the procedural steps in the first example of
// creating a new object $node and setting its 'type' and uid property

    $values = array(
      'type' => 'event',
      'uid' => $user->uid,
      'status' => 1,
      'comment' => 0,
      'promote' => 0,
      'language' => 'et'
    );
    $entity = entity_create('node', $values);
  }

  $ewrapper = entity_metadata_wrapper('node', $entity);
  $ewrapper->title->set($nodeData['title']);
  $ewrapper->field_description->value = $nodeData['body'];
  $ewrapper->field_pui->set($nodeData['pui']);
  $ewrapper->field_source->set(1); //1 - rest service
  $ewrapper->field_type->set('uritus');
  $ewrapper->field_price->set($nodeData['minPrice'] . ' - ' . $nodeData['maxPrice']);
  $ewrapper->field_price_information->set($nodeData['moreInfoLink']);

  if ($nodeData['imageURL']) {
    $ewrapper->field_hasimage->set(1);
    $ewrapper->field_image_url->set($nodeData['imageURL']);
  }

  if (!empty($nodeData['category'])) {
    $ewrapper->field_categories_event->set($nodeData['category']);
  }

  //schedule
  if (!empty($entity->field_schedule['und'])) {
    $s_values = array();
    foreach ($entity->field_schedule['und'] as $s_key => $s_val) {
      $s_values[] = $s_val['value'];
      unset($entity->field_schedule['und'][$s_key]);
    }
    if (!empty($s_values)) {
      entity_delete_multiple('field_collection_item', $s_values);
    }
  }
  $schedule_item = entity_create('field_collection_item', array('field_name' => 'field_schedule'));
  $schedule_item->setHostEntity('entity', $entity);
  $schedule_wrapper = entity_metadata_wrapper('field_collection_item', $schedule_item);
  // Time
  $start_time = strtotime($nodeData['startTime']);
  $end_time = strtotime($nodeData['endTime']);

  if (date('H:i', $start_time) == '00:00') {
    $start_time = strtotime("-5 minutes", $start_time);
  }
  if (isset($end_time)) {
    if (date('H:i', $end_time) == '00:00') {
      $end_time = strtotime("-5 minutes", $end_time);
    }
  }

  $schedule_wrapper->field_schedule_date[0]->set(
    array(
      'value' => $start_time,
      'value2' => $end_time,
      'rrule' => isset($end_time) ? 'RRULE:FREQ=NONE;' : null
  ));

  $latlng = $nodeData['eventLat'] . ',' . $nodeData['eventLng'];
  $city_id = getCityArea($latlng);
  //$place = getAddress($latlng); // We can use this to get address from google maps API

   if ($city_id) {
    $schedule_wrapper->field_schedule_city_id->set($city_id);
   } 

  $schedule_wrapper->field_schedule_place->set($nodeData['eventAddress']);
  $ewrapper->field_map_latlng->set($latlng);
  $ewrapper->field_map_markers->set($latlng);

  //korraldaja
  if (isset($nodeData['organizerCompany'])) {
    $korraldaja_item = entity_create('field_collection_item', array('field_name' => 'field_korraldaja'));
    $korraldaja_item->setHostEntity('entity', $entity);
    $korraldaja_wrapper = entity_metadata_wrapper('field_collection_item', $korraldaja_item);
    $korraldaja_wrapper->field_korraldaja_nimi->set($nodeData['organizerCompany']);
    $korraldaja_wrapper->field_korraldaja_kontakttelefon->set($nodeData['organizerPhone']);
    $korraldaja_wrapper->field_korraldaja_e_post->set($nodeData['organizerEmail']);
  }
  $ewrapper->save();
}

/**
 * checkIfNodeExist()
 * This function will check if item exist node.
 * 
 * @param $pui
 *    Piletilevi ID
 */
function checkIfNodeExist($pui) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->fieldCondition('field_pui', 'value', $pui, '=');
  
  $result = $query->execute();
  if (isset($result['node'])) {
    return true;
  }
  else {
    return false;
  }
}

/**
 * loadNodeByPUI()
 * This function will load item.
 * 
 * @param $pui
 *    Piletilevi ID.
 */
function loadNodeByPUI($pui) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->fieldCondition('field_pui', 'value', $pui, '=');

  $result = $query->execute();
  if ($result) {
    foreach ($result['node'] as $key => $val) {
      $entity_load = entity_load('node', array($key));
      foreach ($entity_load as $ekey => $eval) {
        $entity = $eval;
      }
      return $entity;
    }
  }
  else {
    return null;
  }
}

/**
 * getCityArea()
 * Get city area code.
 * 
 * @param $latlng
 *    Coordination.
 */
function getCityArea($latlng) {
  $city_areas = array(
    2944195 => 'Põhja-Tallinn',
    2944191 => 'Kesklinn',
    2944187 => 'Haabersti',
    2944189 => 'Kristiine',
    2944190 => 'Lasnamäe',
    2944193 => 'Mustamäe',
    2920234 => 'Pirita',
    2944194 => 'Nõmme',
  );

  $data = getGeoCode($latlng);
  $status = $data->status;
  if ($status == "OK") {
    $city_area = findLongNameGivenType("sublocality_level_1", $data->results[0]->address_components, true);
    $result = array_pop(array_keys($city_areas, $city_area));
    return $result;
  }
  else {
    return false;
  }
}

/**
 * getGeoCode()
 * Get geo data.
 * 
 * @param $latlng
 *    Coordination.
 */
function getGeoCode($latlng) {
  $api_key = variable_get('geolocation_googlemaps_api_key', '');
  $url = 'https://maps.googleapis.com/maps/api/geocode/json?key=' . $api_key . '&latlng=' . trim($latlng) . '&sensor=false';
  $json = @file_get_contents($url);
  $data = json_decode($json);
  return $data;
}

/**
 * findLongNameGivenType()
 * Get additional data.
 * 
 * @param $type
 *    Information type.
 * @param $type
 *    Data array.
 */
function findLongNameGivenType($type, $array, $short_name = false) {
  foreach ($array as $value) {
    if (in_array($type, $value->types)) {
      if ($short_name)
        return $value->short_name;
      else
        return $value->long_name;
    }
  }
  return FALSE;
}

/**
 * getAddress()
 * Get address data.
 * 
 * @param $latlng
 *    Coordination.
 */
function getAddress($latlng) {
  $data = getGeoCode($latlng);
  $status = $data->status;
  if ($status == "OK") {
    $address = "";
    $place = findLongNameGivenType("premise", $data->results[0]->address_components, true);
    $street_number = findLongNameGivenType("street_number", $data->results[0]->address_components, true);
    $street = findLongNameGivenType("route", $data->results[0]->address_components, false);
    $town = findLongNameGivenType("locality", $data->results[0]->address_components, true);
    if ($place) {
      $address .= $place . ', ';
    }
    if ($street) {
      $address .= $street . ' ' . $street_number . ', ';
    }
    $address .= $town;

    return $address;
  }
  else {
    return false;
  }
}