name = Kuhuminna Main
description = 1 column layout used on event listing pages
preview = preview.png
template = main-layout

; ========================================
; Regions
; ========================================
regions[top_bar_left] = Top bar left
regions[top_bar_right] = Top bar right
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[footer] = Footer
regions[footer_logo] = Footer Logo
regions[footer_copyright] = Footer Copyright
regions[footer_main_first] = Footer Main First
regions[footer_main_second] = Footer Main Second
regions[footer_main_third] = Footer Main Third
regions[footer_main_fourth] = Footer Main Fourth
regions[footer_bottom] = Footer Bottom

; Stylesheets
stylesheets[all][] = css/layouts/main/main.layout.css
