<?php

require_once 'vendor/autoload.php';

use \Firebase\JWT\JWT;

/**
 * @file
 * Code for the TARA login module.
 */
function huvi_tara_login_menu() {

  $items['taraloginrequest'] = array(
    'title' => 'TARA login return path',
    'description' => "TARA login return path.",
    'page callback' => '_taraloginrequest',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['admin/config/system/huvi_tara_login'] = array(
    'title' => 'TARA login settings',
    'description' => 'Settings of TARA authorisation.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tara_admin_settings'),
    'file' => 'tara.admin.inc',
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function _taraloginrequest() {

  try {
    $oauth2_client = oauth2_client_load('tara');
    $access_token = $oauth2_client->getAccessToken();
  }
  catch (Exception $e) {
    drupal_set_message($e->getMessage(), 'error');
    watchdog('huvi_tara_login', $e->getMessage(), array(), WATCHDOG_ERROR);
  }

  print_r('<pre>');
  print_r($access_token);
  print_r('</pre>');

  return 'test';
}

/**
 * Implements hook_oauth2_clients().
 */
function huvi_tara_login_oauth2_clients() {

  global $base_url;

  // server-side flow
  $oauth2_clients['tara'] = array(
    'token_endpoint' => variable_get('tara_endpoint_token'),
    'auth_flow' => 'server-side',
    'scope' => 'openid',
    'client_id' => variable_get('tara_user_id'),
    'client_secret' => variable_get('tara_user_password'),
    'authorization_endpoint' => variable_get('tara_endpoint_authorize'),
    'redirect_uri' => $base_url . '/taraloginrequest',
  );

  return $oauth2_clients;
}
