<?php

/**
 * @file
 * Code for the TARA login module.
 */
function huvi_tara_login_menu() {

  $items['taraloginrequest'] = array(
    'title' => 'TARA login return path',
    'description' => "TARA login return path.",
    'page callback' => '_taraloginrequest',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function _taraloginrequest() {

  dpm(drupal_get_http_header());

  dpm(drupal_get_query_parameters());

  dpm($_POST);

  dpm($_GET);

  return 'test';
}
