<?php

/**
 * @file
 * Code for the Huvi RSS feeds feature.
 */

include_once 'huvi_rss_feeds.features.inc';

function huvi_rss_feeds_menu() {
  $items = array();

  $items["rss"] = array(
    'title' => t('RSS feeds'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('huvi_rss_feeds_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );  

  return $items;
}

/**
 * Disable manual user registering
 * (only allow registering and logging with ID card via OpenID)
 *
 * Implements hook_form_alter().
 */
function huvi_rss_feeds_form($form, &$form_state) {    
  
  $event_categories = array (0  => t('Muusika'),
    1 => t('Etendused'),
    2 => t('Näitus, muuseum'),
    3 => t('Mess, laat'),
    4 => t('Sport'),
    5=> t('Kino'),
    6 => t('Pidu, klubid'),
    7 => t('Lapsele'), 
    8 => t('Varia')
  );
  $activity_categories = array (0  => t('Muusika'),
    1 => t('Kunst, käsitöö'),
    2 => t('Tantsimine'),
    3 => t('Sport, liikumine'),
    4 => t('Tehnika'),
    5=> t('Keeleõpe'),
    6 => t('Koolitused, kursused'),
    7 => t('Lapsele'), 
    8 => t('Varia')
  );
  $linnaosa = array(
    2944195 => 'Põhja-Tallinn',
    2944191 => 'Kesklinn',    
    2944187 => 'Haabersti',
    2944189 => 'Kristiine',
    2944190 => 'Lasnamäe',
    2944193 => 'Mustamäe',
    2920234 => 'Pirita',
    2944194 => 'Nõmme',
  );
  $form['#attached']['js'] = array(
      drupal_get_path('module', 'huvi_rss_feeds') . '/js/huvi_rss_feeds.js',
  );
  $form['#attached']['css'] = array(
      drupal_get_path('module', 'huvi_rss_feeds') . '/css/huvi_rss_feeds.css',
  );
  $form['#attributes'] = array('class' => 'rss-form');
  if ( $form_state['rss_link'])
  $form['rss_link'] = array(
  '#markup' => '<div class="rss-url" ><p> <a class="feed-link" href="' . $form_state['rss_link'] . '">' . $form_state['rss_link'] . '</a></p>'
    . '<button id="feed_url">' . t('Copy link') . '</button></div>'
); 
  $form['type'] = array(
  '#type' => 'checkboxes',
  '#options' => array('uritus' => t('üritus'), 'huvitegevus' => t('huvitegevus')),
  '#title' => t('Tüüp')
  );  
  $form['event_category'] = array(
  '#type' => 'checkboxes',
  '#options' =>$event_categories,
  '#title' => t('Ürituse kategooriad')
  );  
  $form['activity_category'] = array(
  '#type' => 'checkboxes',
  '#options' =>$activity_categories,
  '#title' => t('Huvitegevuse kategooriad')
  );  
  $form['linnaosa'] = array(
  '#type' => 'checkboxes',
  '#options' =>$linnaosa,
  '#title' => t('Linnaosa')
  );  
  $form['is_free'] = array(
    '#type' =>'checkbox',
  '#title' => t('Tasuta üritus/huvitegevus'),
    );
  $form['is_free'] = array(
  '#type' =>'checkbox',
  '#title' => t('Tasuta üritus/huvitegevus'),
    );
  $form['text'] = array(
    '#type' => 'textfield', 
    '#title' => t('Keywords'),
    );
  
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Get URL'),
  );
 
  return $form;
}

function huvi_rss_feeds_form_submit($form, &$form_state) {
  global $base_path; 
  global $base_url;
  
  $query_arr = array();
  if (isset($form_state['values']['type'])) {
    foreach($form_state['values']['type'] as $key => $val)
      if ($key == $val)
        $query_arr[]= 'type[]=' . $val;
  }
  if (isset($form_state['values']['event_category'])) {
    foreach($form_state['values']['event_category'] as $key => $val)
      if ($key == $val)
        $query_arr[]= 'event_category[]=' . $val;
  }
  if (isset($form_state['values']['activity_category'])) {
    foreach($form_state['values']['activity_category'] as $key => $val)
      if ($key == $val)
        $query_arr[]= 'activity_category[]=' . $val;
  }
  if (isset($form_state['values']['linnaosa'])) {
    foreach($form_state['values']['linnaosa'] as $key => $val)
      if ($key == $val)
        $query_arr[]= 'linnaosa[]=' . $val;
  }
  if (isset($form_state['values']['is_free'])) {
    $query_arr[]= 'is_free[]=' . $form_state['values']['is_free'];
  }
  else 
    $query_arr[]= 'is_free[]=1';
  if (isset($form_state['values']['text']) & !empty($form_state['values']['text'])) {
    $query_arr[]= 'text[]=' . $form_state['values']['text'];
  }
  
   $form_state['rss_link'] = $base_url . $base_path . 'event-rss-feed?' . implode('&', $query_arr);
   $form_state['rebuild'] = TRUE; 
}